### ISSUE TITLE
Net::HTTP::Persistent::Error: too many connection resets

### ISSUE THREAD

**Issue by mattdlh** [geminabox/geminabox#211]
I am running geminabox in a docker container with no auth, ruby version 2.1.2p95, and am able to connect to the web ui and use it successfully. However, when running a bundle install I get the following error:

```
HTTP GET http://10.10.1.40:9292/api/v1/dependencies
Net::HTTP::Persistent::Error: too many connection resets (due to Timeout::Error - Timeout::Error) after 0 requests on 29235920, last used 1442535465.690835 seconds ago
/usr/lib/ruby/1.9.1/net/protocol.rb:146:in `rescue in rbuf_fill'
  /usr/lib/ruby/1.9.1/net/protocol.rb:140:in `rbuf_fill'
  /usr/lib/ruby/1.9.1/net/protocol.rb:122:in `readuntil'
  /usr/lib/ruby/1.9.1/net/protocol.rb:132:in `readline'
  /usr/lib/ruby/1.9.1/net/http.rb:2563:in `read_status_line'
  /usr/lib/ruby/1.9.1/net/http.rb:2552:in `read_new'
  /usr/lib/ruby/1.9.1/net/http.rb:1320:in `block in transport_request'
  /usr/lib/ruby/1.9.1/net/http.rb:1317:in `catch'
  /usr/lib/ruby/1.9.1/net/http.rb:1317:in `transport_request'
  /usr/lib/ruby/1.9.1/net/http.rb:1294:in `request'
  /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/vendor/net/http/persistent.rb:999:in `request'
  /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/fetcher/downloader.rb:45:in `request'
  /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/fetcher/downloader.rb:15:in `fetch'
  /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/fetcher/dependency.rb:7:in `api_available?'
  /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/fetcher.rb:135:in `block in use_api'
  /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/fetcher.rb:135:in `reject!'
  /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/fetcher.rb:135:in `use_api'
  /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/source/rubygems.rb:320:in `select'
  /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/source/rubygems.rb:320:in `api_fetchers'
  /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/source/rubygems.rb:325:in `block in remote_specs'
  /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/index.rb:9:in `build'
  /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/source/rubygems.rb:324:in `remote_specs'
  /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/source/rubygems.rb:81:in `specs'
  /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/definition.rb:211:in `block (2 levels) in index'
  /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/definition.rb:209:in `each'
  /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/definition.rb:209:in `block in index'
  /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/index.rb:9:in `build'
  /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/definition.rb:206:in `index'
  /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/definition.rb:200:in `resolve'
  /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/definition.rb:140:in `specs'
  /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/definition.rb:129:in `resolve_remotely!'
  /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/installer.rb:79:in `run'
  /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/installer.rb:18:in `install'
  /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/cli/install.rb:107:in `run'
  /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/cli.rb:162:in `install'
  /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
  /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
  /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
  /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/cli.rb:10:in `start'
  /var/lib/gems/1.9.1/gems/bundler-1.10.6/bin/bundle:20:in `block in <top (required)>'
  /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
  /var/lib/gems/1.9.1/gems/bundler-1.10.6/bin/bundle:18:in `<top (required)>'
  /usr/local/bin/bundle:23:in `load'
  /usr/local/bin/bundle:23:in `<main>'
Fetching source index from http://10.10.1.40:9292/
```

**Comment by cwninja** [comment]
From the linked issue, it sounds ruby version dependent. Going to close this as a ruby issue, not a geminabox issue.

**Comment by notjames** [comment]
We're having the same issue. Just wondering...is it a Ruby version issue on the server side or the client side?

**Comment by slayer** [comment]
Some issue on 2.4.1

**Comment by sonots** [comment]
Please paste the backtrace which your server outputs to stderr or stdout

**Comment by slayer** [comment]
There is no errors at `geminabox`. 
These errors in `bundle install`
```
Retrying dependency api due to error (4/4): Bundler::HTTPError Network error while fetching http://gems.a.xxxx.com:9292/api/v1/depende
ncies?gems=actionpack%2Cactionview%2Cactivemodel%2Cactivesupport%2Casset_file%2Cbundler%2Ccombustion%2Cgeminabox%2Cminitest%2Cmocha%2Cra
ke%2Crubocop%2Cshoulda%2Csimplecov (too many connection resets (due to Net::ReadTimeout - Net::ReadTimeout) after 0 requests on 47128871
636420, last used 20.8193756 seconds ago)
Query Gemcutter Dependency Endpoint API: bundler,rake,geminabox,minitest,shoulda,mocha,rubocop,combustion,simplecov,activemodel,activesu
pport,actionpack,actionview,asset_file
HTTP GET http://gems.a.xxxx.com:9292/api/v1/dependencies?gems=actionpack%2Cactionview%2Cactivemodel%2Cactivesupport%2Casset_file%2Cbun
dler%2Ccombustion%2Cgeminabox%2Cminitest%2Cmocha%2Crake%2Crubocop%2Cshoulda%2Csimplecov
Bundler::Persistent::Net::HTTP::Persistent::Error: too many connection resets (due to Net::ReadTimeout - Net::ReadTimeout) after 0 reque
sts on 47128871636420, last used 20.813327248 seconds ago
/usr/local/rbenv/versions/2.2.7/lib/ruby/2.2.0/net/protocol.rb:158:in `rescue in rbuf_fill'
  /usr/local/rbenv/versions/2.2.7/lib/ruby/2.2.0/net/protocol.rb:152:in `rbuf_fill'
  /usr/local/rbenv/versions/2.2.7/lib/ruby/2.2.0/net/protocol.rb:134:in `readuntil'
  /usr/local/rbenv/versions/2.2.7/lib/ruby/2.2.0/net/protocol.rb:144:in `readline'
  /usr/local/rbenv/versions/2.2.7/lib/ruby/2.2.0/net/http/response.rb:39:in `read_status_line'
  /usr/local/rbenv/versions/2.2.7/lib/ruby/2.2.0/net/http/response.rb:28:in `read_new'
  /usr/local/rbenv/versions/2.2.7/lib/ruby/2.2.0/net/http.rb:1414:in `block in transport_request'
  /usr/local/rbenv/versions/2.2.7/lib/ruby/2.2.0/net/http.rb:1411:in `catch'
  /usr/local/rbenv/versions/2.2.7/lib/ruby/2.2.0/net/http.rb:1411:in `transport_request'
  /usr/local/rbenv/versions/2.2.7/lib/ruby/2.2.0/net/http.rb:1384:in `request'
  /usr/local/rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/bundler-1.15.1/lib/bundler/vendor/net-http-persistent/lib/net/http/persistent
.rb:999:in `request'
  /usr/local/rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/bundler-1.15.1/lib/bundler/fetcher/downloader.rb:50:in `request'
...
```



That issue is really strange: 
I ran my custom geminbox docker image on server `A` - and `bundle` fails.

After that I started the same docker image locally and `bundle` worked OK. 
After, I ran on server `B` and `bundle` works OK either.
