### ISSUE TITLE
500 error whren try to install font-awesome-rails-4.5.0.1.gem

### ISSUE THREAD

**Issue by pacolotero** [geminabox/geminabox#223]
I get this error (puma stderr) when i try install font-awesome-rails-4.5.0.1.gem
```
2016-02-10 14:05:02 - HTTPClient::BadResponseError - unexpected response: #<HTTP::Message::Headers:0x0000000110ee00 @http_version="1.1", @body_size=0, @chunked=false, @request_method="GET", @request_uri=#<URI::HTTP:0x0000000110fad0 URL:http://production.cf.rubygems.org/gems/font-awesome-rails-4.5.0.1.gem>, @request_query=nil, @request_absolute_uri=nil, @status_code=404, @reason_phrase="Not Found", @body_type=nil, @body_charset=nil, @body_date=nil, @body_encoding=#<Encoding:ASCII-8BIT>, @is_request=false, @header_item=[["Content-Type", "application/xml"], ["Transfer-Encoding", "chunked"], ["Connection", "keep-alive"], ["Date", "Wed, 10 Feb 2016 13:05:13 GMT"], ["Server", "AmazonS3"], ["X-Cache", "Error from cloudfront"], ["Via", "1.1 fdc7ffda73f7904d8d7d693b39a063d9.cloudfront.net (CloudFront)"], ["X-Amz-Cf-Id", "gp9yQuLavNSBgnOIDZQlFPoWCvIq1WvTCXIdo4dPs4vqN7BcDKRdog=="]], @dumped=false>:
	/home/geminabox/.rvm/gems/ruby-2.1.4@gemninabox/gems/httpclient-2.7.1/lib/httpclient.rb:1123:in `success_content'
	/home/geminabox/.rvm/gems/ruby-2.1.4@gemninabox/gems/httpclient-2.7.1/lib/httpclient.rb:651:in `get_content'
	/home/geminabox/.rvm/gems/ruby-2.1.4@gemninabox/gems/geminabox-0.12.4/lib/geminabox/http_adapter/http_client_adapter.rb:12:in `get_content'
	/home/geminabox/.rvm/gems/ruby-2.1.4@gemninabox/gems/geminabox-0.12.4/lib/geminabox/proxy/hostess.rb:64:in `get_from_rubygems_if_not_local'
	/home/geminabox/.rvm/gems/ruby-2.1.4@gemninabox/gems/geminabox-0.12.4/lib/geminabox/proxy/hostess.rb:52:in `block in <class:Hostess>'
	/home/geminabox/.rvm/gems/ruby-2.1.4@gemninabox/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `call'
	/home/geminabox/.rvm/gems/ruby-2.1.4@gemninabox/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `block in compile!'
	/home/geminabox/.rvm/gems/ruby-2.1.4@gemninabox/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `[]'
	/home/geminabox/.rvm/gems/ruby-2.1.4@gemninabox/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (3 levels) in route!'
	/home/geminabox/.rvm/gems/ruby-2.1.4@gemninabox/gems/sinatra-1.4.7/lib/sinatra/base.rb:994:in `route_eval'
	/home/geminabox/.rvm/gems/ruby-2.1.4@gemninabox/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (2 levels) in route!'
	/home/geminabox/.rvm/gems/ruby-2.1.4@gemninabox/gems/sinatra-1.4.7/lib/sinatra/base.rb:1015:in `block in process_route'
	/home/geminabox/.rvm/gems/ruby-2.1.4@gemninabox/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `catch'
	/home/geminabox/.rvm/gems/ruby-2.1.4@gemninabox/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `process_route'
	/home/geminabox/.rvm/gems/ruby-2.1.4@gemninabox/gems/sinatra-1.4.7/lib/sinatra/base.rb:973:in `block in route!'
	/home/geminabox/.rvm/gems/ruby-2.1.4@gemninabox/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `each'
	/home/geminabox/.rvm/gems/ruby-2.1.4@gemninabox/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `route!'
	/home/geminabox/.rvm/gems/ruby-2.1.4@gemninabox/gems/sinatra-1.4.7/lib/sinatra/base.rb:1085:in `block in dispatch!'
	/home/geminabox/.rvm/gems/ruby-2.1.4@gemninabox/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
	/home/geminabox/.rvm/gems/ruby-2.1.4@gemninabox/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
	/home/geminabox/.rvm/gems/ruby-2.1.4@gemninabox/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
	/home/geminabox/.rvm/gems/ruby-2.1.4@gemninabox/gems/sinatra-1.4.7/lib/sinatra/base.rb:1082:in `dispatch!'
	/home/geminabox/.rvm/gems/ruby-2.1.4@gemninabox/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `block in call!'
	/home/geminabox/.rvm/gems/ruby-2.1.4@gemninabox/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
	/home/geminabox/.rvm/gems/ruby-2.1.4@gemninabox/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
	/home/geminabox/.rvm/gems/ruby-2.1.4@gemninabox/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
	/home/geminabox/.rvm/gems/ruby-2.1.4@gemninabox/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `call!'
	/home/geminabox/.rvm/gems/ruby-2.1.4@gemninabox/gems/sinatra-1.4.7/lib/sinatra/base.rb:895:in `call'
	/home/geminabox/.rvm/gems/ruby-2.1.4@gemninabox/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
	/home/geminabox/.rvm/gems/ruby-2.1.4@gemninabox/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
	/home/geminabox/.rvm/gems/ruby-2.1.4@gemninabox/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
	/home/geminabox/.rvm/gems/ruby-2.1.4@gemninabox/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/home/geminabox/.rvm/gems/ruby-2.1.4@gemninabox/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/home/geminabox/.rvm/gems/ruby-2.1.4@gemninabox/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
	/home/geminabox/.rvm/gems/ruby-2.1.4@gemninabox/gems/rack-1.6.4/lib/rack/nulllogger.rb:9:in `call'
	/home/geminabox/.rvm/gems/ruby-2.1.4@gemninabox/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
	/home/geminabox/.rvm/gems/ruby-2.1.4@gemninabox/gems/sinatra-1.4.7/lib/sinatra/base.rb:182:in `call'
	/home/geminabox/.rvm/gems/ruby-2.1.4@gemninabox/gems/sinatra-1.4.7/lib/sinatra/base.rb:2013:in `call'
	/home/geminabox/.rvm/gems/ruby-2.1.4@gemninabox/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
	/home/geminabox/.rvm/gems/ruby-2.1.4@gemninabox/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
	/home/geminabox/.rvm/gems/ruby-2.1.4@gemninabox/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
	/home/geminabox/.rvm/gems/ruby-2.1.4@gemninabox/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/home/geminabox/.rvm/gems/ruby-2.1.4@gemninabox/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/home/geminabox/.rvm/gems/ruby-2.1.4@gemninabox/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
	/home/geminabox/.rvm/gems/ruby-2.1.4@gemninabox/gems/rack-1.6.4/lib/rack/nulllogger.rb:9:in `call'
	/home/geminabox/.rvm/gems/ruby-2.1.4@gemninabox/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
	/home/geminabox/.rvm/gems/ruby-2.1.4@gemninabox/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
	/home/geminabox/.rvm/gems/ruby-2.1.4@gemninabox/gems/sinatra-1.4.7/lib/sinatra/base.rb:182:in `call'
	/home/geminabox/.rvm/gems/ruby-2.1.4@gemninabox/gems/sinatra-1.4.7/lib/sinatra/base.rb:2013:in `call'
	/home/geminabox/.rvm/gems/ruby-2.1.4@gemninabox/gems/sinatra-1.4.7/lib/sinatra/base.rb:1487:in `block in call'
	/home/geminabox/.rvm/gems/ruby-2.1.4@gemninabox/gems/sinatra-1.4.7/lib/sinatra/base.rb:1787:in `synchronize'
	/home/geminabox/.rvm/gems/ruby-2.1.4@gemninabox/gems/sinatra-1.4.7/lib/sinatra/base.rb:1487:in `call'
	/home/geminabox/.rvm/gems/ruby-2.1.4@gemninabox/gems/rack-1.6.4/lib/rack/commonlogger.rb:33:in `call'
	/home/geminabox/.rvm/gems/ruby-2.1.4@gemninabox/gems/sinatra-1.4.7/lib/sinatra/base.rb:219:in `call'
	/home/geminabox/.rvm/gems/ruby-2.1.4@gemninabox/gems/rack-1.6.4/lib/rack/auth/basic.rb:25:in `call'
	/home/geminabox/.rvm/gems/ruby-2.1.4@gemninabox/gems/puma-2.16.0/lib/puma/configuration.rb:81:in `call'
	/home/geminabox/.rvm/gems/ruby-2.1.4@gemninabox/gems/puma-2.16.0/lib/puma/server.rb:557:in `handle_request'
	/home/geminabox/.rvm/gems/ruby-2.1.4@gemninabox/gems/puma-2.16.0/lib/puma/server.rb:404:in `process_client'
	/home/geminabox/.rvm/gems/ruby-2.1.4@gemninabox/gems/puma-2.16.0/lib/puma/server.rb:270:in `block in run'
	/home/geminabox/.rvm/gems/ruby-2.1.4@gemninabox/gems/puma-2.16.0/lib/puma/thread_pool.rb:106:in `call'
	/home/geminabox/.rvm/gems/ruby-2.1.4@gemninabox/gems/puma-2.16.0/lib/puma/thread_pool.rb:106:in `block in spawn_thread'
```
This is my nginx log
GET /gems/font-awesome-rails-4.5.0.1.gem HTTP/1.1" 500 30 "-" "Ruby, RubyGems/2.4.8 x86_64-linux Ruby/2.2.3 (2015-08-18 patchlevel 173)"

**Comment by pacolotero** [comment]
Solved. https://github.com/cwninja/geminabox/pull/1/files
