### ISSUE TITLE
Geminabox::GemStoreError in proxy mode

### ISSUE THREAD

**Issue by hemmrich** [geminabox/geminabox#249]
I'm currently trying to test geminabox's behavior when proxy mode is enabled and rubygems.org is unavailable.

Current configuration:
```
Geminabox.build_legacy = false
Geminabox.rubygems_proxy = true
Geminabox.allow_remote_failure = true
```

I've also modified ```/etc/hosts``` to redirect rubygems.org requests to an unavailable IP address:
```
10.88.206.49 rubygems.org
```
Output when pinging this IP:
```
[hemmrich@disgraceapace geminabox]$ ping 10.88.206.49
PING 10.88.206.49 (10.88.206.49) 56(84) bytes of data.
From 10.88.205.203 icmp_seq=2 Destination Host Unreachable
From 10.88.205.203 icmp_seq=3 Destination Host Unreachable
```

After this setup, when I try to do a ```gem install``` on any gem that I can see on the Geminabox UI, the command fails:
```
[hemmrich@truedrew ~]$ gem fetch actioncable
ERROR:  Could not find a valid gem 'actioncable' (>= 0), here is why:
          Unable to download data from http://<geminabox_host>:9999 - bad response Internal Server Error  500 (http://<geminabox_host>:9999/latest_specs.4.8.gz)
```

Disabling the ```Geminabox.rubygems_proxy``` setting and restarting the server allows the gem to be installed successfully.

Full stack trace for the 500 thrown by Geminabox when in proxy mode:
```
[hemmrich@disgraceapace geminabox]$ rackup --host `hostname` --port 9999
[2016-10-21 20:45:18] INFO  WEBrick 1.3.1
[2016-10-21 20:45:18] INFO  ruby 2.3.1 (2016-04-26) [x86_64-linux]
[2016-10-21 20:45:18] INFO  WEBrick::HTTPServer#start: pid=27353 port=9999
2016-10-21 20:45:27 - Geminabox::GemStoreError - Geminabox::GemStoreError:
	/home/y/lib64/ruby/gems/2.3.0/gems/geminabox-0.13.3/lib/geminabox/proxy/file_handler.rb:48:in `rescue in remote_content'
	/home/y/lib64/ruby/gems/2.3.0/gems/geminabox-0.13.3/lib/geminabox/proxy/file_handler.rb:46:in `remote_content'
	/home/y/lib64/ruby/gems/2.3.0/gems/geminabox-0.13.3/lib/geminabox/proxy/splicer.rb:60:in `merge_gziped_content'
	/home/y/lib64/ruby/gems/2.3.0/gems/geminabox-0.13.3/lib/geminabox/proxy/splicer.rb:48:in `merge_content'
	/home/y/lib64/ruby/gems/2.3.0/gems/geminabox-0.13.3/lib/geminabox/proxy/splicer.rb:28:in `new_content'
	/home/y/lib64/ruby/gems/2.3.0/gems/geminabox-0.13.3/lib/geminabox/proxy/splicer.rb:14:in `create'
	/home/y/lib64/ruby/gems/2.3.0/gems/geminabox-0.13.3/lib/geminabox/proxy/splicer.rb:9:in `make'
	/home/y/lib64/ruby/gems/2.3.0/gems/geminabox-0.13.3/lib/geminabox/proxy/hostess.rb:70:in `splice_file'
	/home/y/lib64/ruby/gems/2.3.0/gems/geminabox-0.13.3/lib/geminabox/proxy/hostess.rb:21:in `block (2 levels) in <class:Hostess>'
	/home/y/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `call'
	/home/y/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `block in compile!'
	/home/y/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (3 levels) in route!'
	/home/y/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:994:in `route_eval'
	/home/y/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (2 levels) in route!'
	/home/y/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1015:in `block in process_route'
	/home/y/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `catch'
	/home/y/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `process_route'
	/home/y/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:973:in `block in route!'
	/home/y/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `each'
	/home/y/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `route!'
	/home/y/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1085:in `block in dispatch!'
	/home/y/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
	/home/y/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
	/home/y/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
	/home/y/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1082:in `dispatch!'
	/home/y/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `block in call!'
	/home/y/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
	/home/y/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
	/home/y/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
	/home/y/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `call!'
	/home/y/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:895:in `call'
	/home/y/lib64/ruby/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
	/home/y/lib64/ruby/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
	/home/y/lib64/ruby/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
	/home/y/lib64/ruby/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/home/y/lib64/ruby/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/home/y/lib64/ruby/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
	/home/y/lib64/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/nulllogger.rb:9:in `call'
	/home/y/lib64/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
	/home/y/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/show_exceptions.rb:25:in `call'
	/home/y/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:182:in `call'
	/home/y/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:2013:in `call'
	/home/y/lib64/ruby/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
	/home/y/lib64/ruby/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
	/home/y/lib64/ruby/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
	/home/y/lib64/ruby/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/home/y/lib64/ruby/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/home/y/lib64/ruby/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
	/home/y/lib64/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/nulllogger.rb:9:in `call'
	/home/y/lib64/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
	/home/y/lib64/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
	/home/y/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/show_exceptions.rb:25:in `call'
	/home/y/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:182:in `call'
	/home/y/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:2013:in `call'
	/home/y/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1487:in `block in call'
	/home/y/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1787:in `synchronize'
	/home/y/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1487:in `call'
	/home/y/lib64/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/tempfile_reaper.rb:15:in `call'
	/home/y/lib64/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/lint.rb:49:in `_call'
	/home/y/lib64/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/lint.rb:37:in `call'
	/home/y/lib64/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/showexceptions.rb:24:in `call'
	/home/y/lib64/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/commonlogger.rb:33:in `call'
	/home/y/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:219:in `call'
	/home/y/lib64/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/chunked.rb:54:in `call'
	/home/y/lib64/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/content_length.rb:15:in `call'
	/home/y/lib64/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/handler/webrick.rb:88:in `service'
	/home/y/lib64/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
	/home/y/lib64/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
	/home/y/lib64/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'
10.91.26.123 - - [21/Oct/2016:20:45:27 +0000] "GET /latest_specs.4.8.gz HTTP/1.1" 500 192624 3.0979
2016-10-21 20:45:30 - Geminabox::GemStoreError - Geminabox::GemStoreError:
	/home/y/lib64/ruby/gems/2.3.0/gems/geminabox-0.13.3/lib/geminabox/proxy/file_handler.rb:48:in `rescue in remote_content'
	/home/y/lib64/ruby/gems/2.3.0/gems/geminabox-0.13.3/lib/geminabox/proxy/file_handler.rb:46:in `remote_content'
	/home/y/lib64/ruby/gems/2.3.0/gems/geminabox-0.13.3/lib/geminabox/proxy/splicer.rb:60:in `merge_gziped_content'
	/home/y/lib64/ruby/gems/2.3.0/gems/geminabox-0.13.3/lib/geminabox/proxy/splicer.rb:48:in `merge_content'
	/home/y/lib64/ruby/gems/2.3.0/gems/geminabox-0.13.3/lib/geminabox/proxy/splicer.rb:28:in `new_content'
	/home/y/lib64/ruby/gems/2.3.0/gems/geminabox-0.13.3/lib/geminabox/proxy/splicer.rb:14:in `create'
	/home/y/lib64/ruby/gems/2.3.0/gems/geminabox-0.13.3/lib/geminabox/proxy/splicer.rb:9:in `make'
	/home/y/lib64/ruby/gems/2.3.0/gems/geminabox-0.13.3/lib/geminabox/proxy/hostess.rb:70:in `splice_file'
	/home/y/lib64/ruby/gems/2.3.0/gems/geminabox-0.13.3/lib/geminabox/proxy/hostess.rb:21:in `block (2 levels) in <class:Hostess>'
	/home/y/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `call'
	/home/y/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `block in compile!'
	/home/y/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (3 levels) in route!'
	/home/y/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:994:in `route_eval'
	/home/y/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (2 levels) in route!'
	/home/y/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1015:in `block in process_route'
	/home/y/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `catch'
	/home/y/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `process_route'
	/home/y/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:973:in `block in route!'
	/home/y/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `each'
	/home/y/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `route!'
	/home/y/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1085:in `block in dispatch!'
	/home/y/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
	/home/y/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
	/home/y/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
	/home/y/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1082:in `dispatch!'
	/home/y/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `block in call!'
	/home/y/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
	/home/y/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
	/home/y/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
	/home/y/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `call!'
	/home/y/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:895:in `call'
	/home/y/lib64/ruby/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
	/home/y/lib64/ruby/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
	/home/y/lib64/ruby/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
	/home/y/lib64/ruby/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/home/y/lib64/ruby/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/home/y/lib64/ruby/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
	/home/y/lib64/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/nulllogger.rb:9:in `call'
	/home/y/lib64/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
	/home/y/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/show_exceptions.rb:25:in `call'
	/home/y/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:182:in `call'
	/home/y/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:2013:in `call'
	/home/y/lib64/ruby/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
	/home/y/lib64/ruby/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
	/home/y/lib64/ruby/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
	/home/y/lib64/ruby/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/home/y/lib64/ruby/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/home/y/lib64/ruby/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
	/home/y/lib64/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/nulllogger.rb:9:in `call'
	/home/y/lib64/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
	/home/y/lib64/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
	/home/y/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/show_exceptions.rb:25:in `call'
	/home/y/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:182:in `call'
	/home/y/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:2013:in `call'
	/home/y/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1487:in `block in call'
	/home/y/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1787:in `synchronize'
	/home/y/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1487:in `call'
	/home/y/lib64/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/tempfile_reaper.rb:15:in `call'
	/home/y/lib64/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/lint.rb:49:in `_call'
	/home/y/lib64/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/lint.rb:37:in `call'
	/home/y/lib64/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/showexceptions.rb:24:in `call'
	/home/y/lib64/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/commonlogger.rb:33:in `call'
	/home/y/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:219:in `call'
	/home/y/lib64/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/chunked.rb:54:in `call'
	/home/y/lib64/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/content_length.rb:15:in `call'
	/home/y/lib64/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/handler/webrick.rb:88:in `service'
	/home/y/lib64/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
	/home/y/lib64/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
	/home/y/lib64/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'
10.91.26.123 - - [21/Oct/2016:20:45:30 +0000] "GET /latest_specs.4.8.gz HTTP/1.1" 500 192624 2.7875
```

I assume this has something to do with the hardcoded rubygems.org url in [proxy/file_handler.rb](https://github.com/geminabox/geminabox/blob/master/lib/geminabox/proxy/file_handler.rb) in the ```remote_content``` function at line 52.

**Comment by sonots** [comment]
Could you try https://github.com/geminabox/geminabox/pull/250 this branch?

**Comment by hemmrich** [comment]
@sonots #250 works! Thank you for fixing this issue so quickly 😄

**Comment by sonots** [comment]
Good to hear. I merged.

**Comment by sonots** [comment]
0.13.4 is released
