### ISSUE TITLE
Unable to activate sinatra-1.4.8, because rack-2.0.1 conflicts with rack

### ISSUE THREAD

**Issue by thebravoman** [geminabox/geminabox#266]
I keep getting this error and I can not track it down on why it occurs. 

The source is without any modification from the repo:

/usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:2112:in `raise_if_conflicts': Unable to activate sinatra-1.4.8, because rack-2.0.1 conflicts with rack (~> 1.5) (Gem::ConflictError)
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1280:in `activate'
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rubygems.rb:198:in `rescue in try_activate'
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rubygems.rb:195:in `try_activate'
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:126:in `rescue in require'
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from /home/gemserver/geminabox/lib/geminabox.rb:4:in `<top (required)>'
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/gemserver/geminabox/config.ru:2:in `block in <main>'
	from /usr/local/rvm/gems/ruby-2.2.2/gems/rack-2.0.1/lib/rack/builder.rb:55:in `instance_eval'
	from /usr/local/rvm/gems/ruby-2.2.2/gems/rack-2.0.1/lib/rack/builder.rb:55:in `initialize'
	from /home/gemserver/geminabox/config.ru:in `new'
	from /home/gemserver/geminabox/config.ru:in `<main>'
	from /usr/local/rvm/gems/ruby-2.2.2/gems/rack-2.0.1/lib/rack/builder.rb:49:in `eval'
	from /usr/local/rvm/gems/ruby-2.2.2/gems/rack-2.0.1/lib/rack/builder.rb:49:in `new_from_string'
	from /usr/local/rvm/gems/ruby-2.2.2/gems/rack-2.0.1/lib/rack/builder.rb:40:in `parse_file'
	from /usr/local/rvm/gems/ruby-2.2.2/gems/rack-2.0.1/lib/rack/server.rb:318:in `build_app_and_options_from_config'
	from /usr/local/rvm/gems/ruby-2.2.2/gems/rack-2.0.1/lib/rack/server.rb:218:in `app'
	from /usr/local/rvm/gems/ruby-2.2.2/gems/rack-2.0.1/lib/rack/server.rb:353:in `wrapped_app'
	from /usr/local/rvm/gems/ruby-2.2.2/gems/rack-2.0.1/lib/rack/server.rb:282:in `start'
	from /usr/local/rvm/gems/ruby-2.2.2/gems/rack-2.0.1/lib/rack/server.rb:147:in `start'
	from /usr/local/rvm/gems/ruby-2.2.2/gems/rack-2.0.1/bin/rackup:4:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.2.2/bin/rackup:23:in `load'
	from /usr/local/rvm/gems/ruby-2.2.2/bin/rackup:23:in `<main>'

**Comment by thebravoman** [comment]
Turns out I had to remote rack-2.0.1
