### ISSUE TITLE
RuntimeError - unknown file type

### ISSUE THREAD

**Issue by sonots** [geminabox/geminabox#267]
I sometimes encounter `RuntimeError - unknown file type` error on proxy mode: 

1st pattern (happens on force_rebuild)

```
2017-05-22 14:08:49 - RuntimeError - unknown file type: /tmp/gem_generate_index_27167/specs.4.8.gz:
      .rbenv/versions/2.1.5/lib/ruby/2.1.0/fileutils.rb:1396:in `copy'
      .rbenv/versions/2.1.5/lib/ruby/2.1.0/fileutils.rb:469:in `block in copy_entry'
      .rbenv/versions/2.1.5/lib/ruby/2.1.0/fileutils.rb:1506:in `call'
      .rbenv/versions/2.1.5/lib/ruby/2.1.0/fileutils.rb:1506:in `wrap_traverse'
      .rbenv/versions/2.1.5/lib/ruby/2.1.0/fileutils.rb:466:in `copy_entry'
      .rbenv/versions/2.1.5/lib/ruby/2.1.0/fileutils.rb:527:in `rescue in block in mv'
      .rbenv/versions/2.1.5/lib/ruby/2.1.0/fileutils.rb:524:in `block in mv'
      .rbenv/versions/2.1.5/lib/ruby/2.1.0/fileutils.rb:1579:in `block in fu_each_src_dest'
      .rbenv/versions/2.1.5/lib/ruby/2.1.0/fileutils.rb:1593:in `fu_each_src_dest0'
      .rbenv/versions/2.1.5/lib/ruby/2.1.0/fileutils.rb:1577:in `fu_each_src_dest'
      .rbenv/versions/2.1.5/lib/ruby/2.1.0/fileutils.rb:514:in `mv'
      .rbenv/versions/2.1.5/lib/ruby/2.1.0/rubygems/indexer.rb:357:in `block in install_indicies'
      .rbenv/versions/2.1.5/lib/ruby/2.1.0/rubygems/indexer.rb:352:in `each'
      .rbenv/versions/2.1.5/lib/ruby/2.1.0/rubygems/indexer.rb:352:in `install_indicies'
      .rbenv/versions/2.1.5/lib/ruby/2.1.0/rubygems/indexer.rb:311:in `generate_index'
      vendor/bundle/ruby/2.1.0/gems/geminabox-0.13.5/lib/geminabox/server.rb:55:in `reindex'
      vendor/bundle/ruby/2.1.0/gems/geminabox-0.13.5/lib/geminabox/server.rb:66:in `rescue in reindex'
      vendor/bundle/ruby/2.1.0/gems/geminabox-0.13.5/lib/geminabox/server.rb:58:in `reindex'
      vendor/bundle/ruby/2.1.0/gems/geminabox-0.13.5/lib/geminabox/gem_store.rb:82:in `write_and_index'
      vendor/bundle/ruby/2.1.0/gems/geminabox-0.13.5/lib/geminabox/gem_store.rb:20:in `save'
      vendor/bundle/ruby/2.1.0/gems/geminabox-0.13.5/lib/geminabox/gem_store.rb:8:in `create'
      vendor/bundle/ruby/2.1.0/gems/geminabox-0.13.5/lib/geminabox/proxy/hostess.rb:64:in `get_from_rubygems_if_not_local'
      vendor/bundle/ruby/2.1.0/gems/geminabox-0.13.5/lib/geminabox/proxy/hostess.rb:51:in `block in <class:Hostess>'
      vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `call'
      vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `block in compile!'
      vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `[]'
      vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (3 levels) in route!'
      vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:994:in `route_eval'
      vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (2 levels) in route!'
      vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1015:in `block in process_route'
      vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `catch'
      vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `process_route'
      vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:973:in `block in route!'
      vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `each'
      vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `route!'
      vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1085:in `block in dispatch!'
      vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
      vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
      vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
      vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1082:in `dispatch!'
      vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `block in call!'
      vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
      vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
      vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
      vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `call!'
      vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:895:in `call'
```

**Comment by sonots** [comment]
2nd pattern

```
RuntimeError:unknown file type: /tmp/gem_generate_index_27167/quick/Marshal.4.8/actionview-5.1.1.gemspec.rz
.rbenv/versions/2.1.5/lib/ruby/2.1.0/fileutils.rb:1396:in `copy'
.rbenv/versions/2.1.5/lib/ruby/2.1.0/fileutils.rb:469:in `block in copy_entry'
.rbenv/versions/2.1.5/lib/ruby/2.1.0/fileutils.rb:1506:in `call'
.rbenv/versions/2.1.5/lib/ruby/2.1.0/fileutils.rb:1506:in `wrap_traverse'
.rbenv/versions/2.1.5/lib/ruby/2.1.0/fileutils.rb:466:in `copy_entry'
.rbenv/versions/2.1.5/lib/ruby/2.1.0/fileutils.rb:527:in `rescue in block in mv'
.rbenv/versions/2.1.5/lib/ruby/2.1.0/fileutils.rb:524:in `block in mv'
.rbenv/versions/2.1.5/lib/ruby/2.1.0/fileutils.rb:1579:in `block in fu_each_src_dest'
.rbenv/versions/2.1.5/lib/ruby/2.1.0/fileutils.rb:1595:in `fu_each_src_dest0'
.rbenv/versions/2.1.5/lib/ruby/2.1.0/fileutils.rb:1577:in `fu_each_src_dest'
.rbenv/versions/2.1.5/lib/ruby/2.1.0/fileutils.rb:514:in `mv'
.rbenv/versions/2.1.5/lib/ruby/2.1.0/rubygems/indexer.rb:474:in `block in update_index'
.rbenv/versions/2.1.5/lib/ruby/2.1.0/rubygems/indexer.rb:468:in `each'
.rbenv/versions/2.1.5/lib/ruby/2.1.0/rubygems/indexer.rb:468:in `update_index'
vendor/bundle/ruby/2.1.0/gems/geminabox-0.13.5/lib/geminabox/server.rb:63:in `reindex'
vendor/bundle/ruby/2.1.0/gems/geminabox-0.13.5/lib/geminabox/gem_store.rb:82:in `write_and_index'
vendor/bundle/ruby/2.1.0/gems/geminabox-0.13.5/lib/geminabox/gem_store.rb:20:in `save'
vendor/bundle/ruby/2.1.0/gems/geminabox-0.13.5/lib/geminabox/gem_store.rb:8:in `create'
vendor/bundle/ruby/2.1.0/gems/geminabox-0.13.5/lib/geminabox/proxy/hostess.rb:64:in `get_from_rubygems_if_not_local'
vendor/bundle/ruby/2.1.0/gems/geminabox-0.13.5/lib/geminabox/proxy/hostess.rb:51:in `block in <class:Hostess>'
vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `call'
vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `block in compile!'
vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `[]'
vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (3 levels) in route!'
vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:994:in `route_eval'
vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (2 levels) in route!'
vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1015:in `block in process_route'
vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `catch'
vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `process_route'
vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:973:in `block in route!'
vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `each'
vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `route!'
vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1085:in `block in dispatch!'
vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1082:in `dispatch!'
vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `block in call!'
vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `call!'
vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:895:in `call
```

**Comment by sonots** [comment]
This would be caused by concurrent reindex(:force_rebuild), and would be fixed by https://github.com/geminabox/geminabox/pull/276

**Comment by sonots** [comment]
After deployed #276, I don't see the error on my environment.
