### ISSUE TITLE
Errno::ENOENT - No such file or directory @ rb_sysopen

### ISSUE THREAD

**Issue by sonots** [geminabox/geminabox#268]
I sometimes encounter Errno::ENOENT error as on proxy mode as:

(happens on force_rebuild)

```
2016-12-21 11:50:27 - Errno::ENOENT - No such file or directory @ rb_sysopen - /tmp/gem_generate_index_10579/quick/Marshal.4.8/ADB-0.5.6.gemspec.rz:
      lib/ruby/2.1.0/open-uri.rb:36:in `initialize'
      lib/ruby/2.1.0/open-uri.rb:36:in `open'
      lib/ruby/2.1.0/open-uri.rb:36:in `open'
      lib/ruby/2.1.0/rubygems/indexer.rb:143:in `block (2 levels) in build_marshal_gemspecs'
      lib/ruby/2.1.0/rubygems/specification.rb:883:in `block in each'
      lib/ruby/2.1.0/rubygems/specification.rb:882:in `each'
      lib/ruby/2.1.0/rubygems/specification.rb:882:in `each'
      lib/ruby/2.1.0/rubygems/indexer.rb:137:in `block in build_marshal_gemspecs'
      lib/ruby/2.1.0/rubygems.rb:899:in `time'
      lib/ruby/2.1.0/rubygems/indexer.rb:136:in `build_marshal_gemspecs'
      lib/ruby/2.1.0/rubygems/indexer.rb:119:in `build_indicies'
      lib/ruby/2.1.0/rubygems/indexer.rb:310:in `generate_index'
      vendor/bundle/ruby/2.1.0/gems/geminabox-0.13.1/lib/geminabox/server.rb:50:in `reindex'
      vendor/bundle/ruby/2.1.0/gems/geminabox-0.13.1/lib/geminabox/server.rb:64:in `rescue in reindex'
      vendor/bundle/ruby/2.1.0/gems/geminabox-0.13.1/lib/geminabox/server.rb:53:in `reindex'
      vendor/bundle/ruby/2.1.0/gems/geminabox-0.13.1/lib/geminabox/gem_store.rb:82:in `write_and_index'
      vendor/bundle/ruby/2.1.0/gems/geminabox-0.13.1/lib/geminabox/gem_store.rb:20:in `save'
      vendor/bundle/ruby/2.1.0/gems/geminabox-0.13.1/lib/geminabox/gem_store.rb:8:in `create'
      vendor/bundle/ruby/2.1.0/gems/geminabox-0.13.1/lib/geminabox/proxy/hostess.rb:65:in `get_from_rubygems_if_not_local'
      vendor/bundle/ruby/2.1.0/gems/geminabox-0.13.1/lib/geminabox/proxy/hostess.rb:52:in `block in <class:Hostess>'
      vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `call'
      vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `block in compile!'
      vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `[]'
      vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (3 levels) in route!'
      vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:994:in `route_eval'
      vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (2 levels) in route!'
      vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1015:in `block in process_route'
      vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `catch'
      vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `process_route'
      vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:973:in `block in route!'
      vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `each'
      vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `route!'
      vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1085:in `block in dispatch!'
      vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
      vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
      vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
      vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1082:in `dispatch!'
      vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `block in call!'
      vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
      vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
      vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
      vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `call!'
      vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:895:in `call'
      vendor/bundle/ruby/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
      vendor/bundle/ruby/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
      vendor/bundle/ruby/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
      vendor/bundle/ruby/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
      vendor/bundle/ruby/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
      vendor/bundle/ruby/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
      vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/nulllogger.rb:9:in `call'
      vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
      vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:182:in `call'
      vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:2013:in `call'
      vendor/bundle/ruby/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
      vendor/bundle/ruby/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
      vendor/bundle/ruby/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
      vendor/bundle/ruby/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
      vendor/bundle/ruby/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
      vendor/bundle/ruby/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
      vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/nulllogger.rb:9:in `call'
      vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
      vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
      vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:182:in `call'
      vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:2013:in `call
      vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1487:in `block in call'
      vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1787:in `synchronize'
      vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1487:in `call'
      vendor/bundle/ruby/2.1.0/gems/rack-ltsv_logger-0.0.3/lib/rack/ltsv_logger.rb:14:in `call'
      vendor/bundle/ruby/2.1.0/gems/puma-3.6.0/lib/puma/configuration.rb:225:in `call'
      vendor/bundle/ruby/2.1.0/gems/puma-3.6.0/lib/puma/server.rb:578:in `handle_request'
      vendor/bundle/ruby/2.1.0/gems/puma-3.6.0/lib/puma/server.rb:415:in `process_client'
      vendor/bundle/ruby/2.1.0/gems/puma-3.6.0/lib/puma/server.rb:275:in `block in run'
      vendor/bundle/ruby/2.1.0/gems/puma-3.6.0/lib/puma/thread_pool.rb:116:in `call'
      vendor/bundle/ruby/2.1.0/gems/puma-3.6.0/lib/puma/thread_pool.rb:116:in `block in spawn_thread'
```

**Comment by sonots** [comment]
This would be caused by concurrent reindex(:force_rebuild), and would be fixed by https://github.com/geminabox/geminabox/pull/276

**Comment by sonots** [comment]
After deployed #276, I don't see the error on my environment.
