### ISSUE TITLE
Fix indexing infinite recursion

### ISSUE THREAD

**Issue by jmellor** [geminabox/geminabox#286]
We had a not-so-bright dev pull *.gem multiple times, which pulled a fairly large number of gems through from upstream before falling over.  Unfortunately, upstream appears to have a defective gem that causes geminabox indexing to fall over.

The first noted symptom is a permanent 100% processor looping while performing the next Marshal indexing after the "event".  Recovery does not seem possible, except by going to backups.

Please add an excessive recursion check, and handling to skip the gem causing the problem.

**Comment by sonots** [comment]
Did you find the defective gem? If you can provide the information, I can deeply investigate it.

**Comment by jmellor** [comment]
Our repo was at about 2450 gems.  The defective gem was somewhere in a*.gem.  Unfortunately I am unable to narrow it down further, as in the heat of the recovery battle, I was doing broad-swathe gem deletions to get back into operation.  After getting back into operation, the repo is currently at arounf 1128 gems.

**Comment by jmellor** [comment]
This issue was originally reported as a problem with the spoonest/geminabox docker image.  See https://github.com/yuri-karpovich/geminabox/issues/1#issuecomment-333979916 for details of that conversation.  Most recently, the image owner stated that this was an underlying problem in geminabox and not his image; hence this ticket.

**Comment by sonots** [comment]
I looked your log, and yep, it looked wierd:

```
/usr/local/bundle/gems/rack-2.0.3/lib/rack/handler/webrick.rb:86:in `service'
/usr/local/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
/usr/local/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
/usr/local/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'
...................................................................................................................
Complete
Generated Marshal quick index gemspecs: 2227.480s
ArgumentError:comparison of Array with Array failed
/usr/local/lib/ruby/site_ruby/2.3.0/rubygems/indexer.rb:428:in `sort'
/usr/local/lib/ruby/site_ruby/2.3.0/rubygems/indexer.rb:428:in `update_specs_index'
/usr/local/lib/ruby/site_ruby/2.3.0/rubygems/indexer.rb:380:in `block in update_index'
/usr/local/lib/ruby/site_ruby/2.3.0/rubygems.rb:1022:in `time'
/usr/local/lib/ruby/site_ruby/2.3.0/rubygems/indexer.rb:379:in `update_index'
/usr/local/bundle/gems/geminabox-0.13.4/lib/geminabox/server.rb:63:in `reindex'
/usr/local/bundle/gems/geminabox-0.13.4/lib/geminabox/gem_store.rb:82:in `write_and_index'
/usr/local/bundle/gems/geminabox-0.13.4/lib/geminabox/gem_store.rb:20:in `save'
/usr/local/bundle/gems/geminabox-0.13.4/lib/geminabox/gem_store.rb:8:in `create'
/usr/local/bundle/gems/geminabox-0.13.4/lib/geminabox/proxy/hostess.rb:64:in `get_from_rubygems_if_not_local'
/usr/local/bundle/gems/geminabox-0.13.4/lib/geminabox/proxy/hostess.rb:51:in `block in <class:Hostess>'
/usr/local/bundle/gems/sinatra-2.0.0/lib/sinatra/base.rb:1632:in `call'
/usr/local/bundle/gems/sinatra-2.0.0/lib/sinatra/base.rb:1632:in `block in compile!'
/usr/local/bundle/gems/sinatra-2.0.0/lib/sinatra/base.rb:991:in `block (3 levels) in route!'
/usr/local/bundle/gems/sinatra-2.0.0/lib/sinatra/base.rb:1010:in `route_eval'
/usr/local/bundle/gems/sinatra-2.0.0/lib/sinatra/base.rb:991:in `block (2 levels) in route!'
/usr/local/bundle/gems/sinatra-2.0.0/lib/sinatra/base.rb:1037:in `block in process_route'
/usr/local/bundle/gems/sinatra-2.0.0/lib/sinatra/base.rb:1035:in `catch'
/usr/local/bundle/gems/sinatra-2.0.0/lib/sinatra/base.rb:1035:in `process_route'
/usr/local/bundle/gems/sinatra-2.0.0/lib/sinatra/base.rb:989:in `block in route!'
/usr/local/bundle/gems/sinatra-2.0.0/lib/sinatra/base.rb:988:in `each'
/usr/local/bundle/gems/sinatra-2.0.0/lib/sinatra/base.rb:988:in `route!'
/usr/local/bundle/gems/sinatra-2.0.0/lib/sinatra/base.rb:1094:in `block in dispatch!'
/usr/local/bundle/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `block in invoke'
/usr/local/bundle/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `catch'
/usr/local/bundle/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `invoke'
/usr/local/bundle/gems/sinatra-2.0.0/lib/sinatra/base.rb:1091:in `dispatch!'
/usr/local/bundle/gems/sinatra-2.0.0/lib/sinatra/base.rb:923:in `block in call!'
/usr/local/bundle/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `block in invoke'
/usr/local/bundle/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `catch'
/usr/local/bundle/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `invoke'
/usr/local/bundle/gems/sinatra-2.0.0/lib/sinatra/base.rb:923:in `call!'
/usr/local/bundle/gems/sinatra-2.0.0/lib/sinatra/base.rb:913:in `call'
```

`ArgumentError:comparison of Array with Array failed` is the error, and it is caused by rubygems rather than geminabox. hmm 🤔

**Comment by sonots** [comment]
The error occurs when we sort unmatched type array as:

```
irb(main):003:0> array = [["12", 5, 6],["4",2,3],[1,8,9]]
=> [["12", 5, 6], ["4", 2, 3], [1, 8, 9]]
irb(main):004:0> array.sort
ArgumentError: comparison of Array with Array failed
```

**Comment by sonots** [comment]
/usr/local/lib/ruby/site_ruby/2.3.0/rubygems/indexer.rb:428:in `sort'

```
415   ##
416   # Combines specs in +index+ and +source+ then writes out a new copy to
417   # +dest+.  For a latest index, does not ensure the new file is minimal.
418
419   def update_specs_index(index, source, dest)
420     specs_index = Marshal.load Gem.read_binary(source)
421
422     index.each do |spec|
423       platform = spec.original_platform
424       platform = Gem::Platform::RUBY if platform.nil? or platform.empty?
425       specs_index << [spec.name, spec.version, platform]
426     end
427
428     specs_index = compact_specs specs_index.uniq.sort
429
430     open dest, 'wb' do |io|
431       Marshal.dump specs_index, io
432     end
433   end
434 end
```

yep, it looks a defective gem caused `comparison of Array with Array failed` error.

**Comment by sonots** [comment]
With https://github.com/geminabox/geminabox/pull/276, I made geminabox not to run reindex concurrently with multiple threads (puma) or processes (unicorn). But, I did not avoid infinite loop.

Applying a patch avoiding `reindex(:force_rebuild)` => `reindex(:force_rebuild)` => `reindex(:force_rebuild)` forever is reasonable.

**Comment by chandru9279** [comment]
Hi When I try `/specs.4.8.gz` on a geminabox install it take a lot of time to get the same Is it related to this infinite loop issue?

**Comment by sonots** [comment]
Not sure with out error messages. Please paste error messages.

**Comment by chandru9279** [comment]
```bash
 wget http://rubygems.org/latest_specs.4.8.gz
--2017-10-10 10:55:14--  http://rubygems.org/latest_specs.4.8.gz
Resolving rubygems.org (rubygems.org)... 172.16.20.240
Connecting to rubygems.org (rubygems.org)|172.16.20.240|:80... connected.
HTTP request sent, awaiting response... 502 Bad Gateway
2017-10-10 10:56:14 ERROR 502: Bad Gateway.
```

I get bad gateway error. I have mapped rubygems.org to the machine where geminabox is running via `/etc/hosts` file.

Im trying to download the gem called `ruby-shadow` which needs the `latest_specs.4.8.gz` file

**Comment by sonots** [comment]
Did not you get any error messages from geminabox server?
Could you paste error messages on the geminabox server?

**Comment by sonots** [comment]
I tried to get ruby-shadow gem, but I could not reproduce on my local machine.

```
Generating Marshal quick index gemspecs for 4 gems
....
Complete
Generated Marshal quick index gemspecs: 0.005s
Updated indexes: 0.001s
Compressing indices
Compressed indices: 0.001s
127.0.0.1 - - [10/Oct/2017:18:27:39 +0900] "GET /gems/ruby-shadow-2.5.0.gem HTTP/1.1" 200 11264 0.0694
```

wget http://localhost:9292/latest_specs.4.8.gz

```
127.0.0.1 - - [10/Oct/2017:18:28:07 +0900] "GET /api/v1/dependencies?gems=ruby-shadow HTTP/1.1" 200 618 0.0130
127.0.0.1 - - [10/Oct/2017:18:28:07 +0900] "GET /api/v1/dependencies HTTP/1.1" 200 - 0.0014
127.0.0.1 - - [10/Oct/2017:18:28:58 +0900] "GET /latest_specs.4.8.gz HTTP/1.1" 200 1151780 2.1475
```
