### ISSUE TITLE
NameError - uninitialized constant Gem::Util:

### ISSUE THREAD

**Issue by shinenelson** [geminabox/geminabox#321]
I'm getting `NameError - uninitialized constant Gem::Util:` with the latest version 1.1.1 on rubygems.org

```
2019-04-16 17:45:55 - NameError - uninitialized constant Gem::Util:
	/var/lib/gems/2.3.0/gems/geminabox-1.1.1/lib/geminabox/server.rb:247:in `block in all_gems_with_duplicates'
	/var/lib/gems/2.3.0/gems/geminabox-1.1.1/lib/geminabox/server.rb:245:in `map'
	/var/lib/gems/2.3.0/gems/geminabox-1.1.1/lib/geminabox/server.rb:245:in `all_gems_with_duplicates'
	/var/lib/gems/2.3.0/gems/geminabox-1.1.1/lib/geminabox/server.rb:241:in `all_gems'
	/var/lib/gems/2.3.0/gems/geminabox-1.1.1/lib/geminabox/server.rb:269:in `load_gems'
	/var/lib/gems/2.3.0/gems/geminabox-1.1.1/lib/geminabox/server.rb:90:in `block in <class:Server>'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1635:in `call'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1635:in `block in compile!'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:992:in `block (3 levels) in route!'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1011:in `route_eval'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:992:in `block (2 levels) in route!'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1040:in `block in process_route'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1038:in `catch'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1038:in `process_route'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:990:in `block in route!'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:989:in `each'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:989:in `route!'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1097:in `block in dispatch!'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `block in invoke'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `catch'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `invoke'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1094:in `dispatch!'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:924:in `block in call!'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `block in invoke'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `catch'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `invoke'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:924:in `call!'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:913:in `call'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:971:in `forward'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1056:in `route_missing'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1006:in `route!'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1002:in `route!'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1097:in `block in dispatch!'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `block in invoke'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `catch'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `invoke'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1094:in `dispatch!'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:924:in `block in call!'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `block in invoke'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `catch'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `invoke'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:924:in `call!'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:913:in `call'
	/var/lib/gems/2.3.0/gems/rack-protection-2.0.5/lib/rack/protection/xss_header.rb:18:in `call'
	/var/lib/gems/2.3.0/gems/rack-protection-2.0.5/lib/rack/protection/path_traversal.rb:16:in `call'
	/var/lib/gems/2.3.0/gems/rack-protection-2.0.5/lib/rack/protection/json_csrf.rb:26:in `call'
	/var/lib/gems/2.3.0/gems/rack-protection-2.0.5/lib/rack/protection/base.rb:50:in `call'
	/var/lib/gems/2.3.0/gems/rack-protection-2.0.5/lib/rack/protection/base.rb:50:in `call'
	/var/lib/gems/2.3.0/gems/rack-protection-2.0.5/lib/rack/protection/frame_options.rb:31:in `call'
	/var/lib/gems/2.3.0/gems/rack-2.0.7/lib/rack/null_logger.rb:9:in `call'
	/var/lib/gems/2.3.0/gems/rack-2.0.7/lib/rack/head.rb:12:in `call'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.5/lib/sinatra/show_exceptions.rb:22:in `call'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:194:in `call'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1957:in `call'
	/var/lib/gems/2.3.0/gems/rack-protection-2.0.5/lib/rack/protection/xss_header.rb:18:in `call'
	/var/lib/gems/2.3.0/gems/rack-protection-2.0.5/lib/rack/protection/path_traversal.rb:16:in `call'
	/var/lib/gems/2.3.0/gems/rack-protection-2.0.5/lib/rack/protection/json_csrf.rb:26:in `call'
	/var/lib/gems/2.3.0/gems/rack-protection-2.0.5/lib/rack/protection/base.rb:50:in `call'
	/var/lib/gems/2.3.0/gems/rack-protection-2.0.5/lib/rack/protection/base.rb:50:in `call'
	/var/lib/gems/2.3.0/gems/rack-protection-2.0.5/lib/rack/protection/frame_options.rb:31:in `call'
	/var/lib/gems/2.3.0/gems/rack-2.0.7/lib/rack/null_logger.rb:9:in `call'
	/var/lib/gems/2.3.0/gems/rack-2.0.7/lib/rack/head.rb:12:in `call'
	/var/lib/gems/2.3.0/gems/rack-2.0.7/lib/rack/method_override.rb:22:in `call'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.5/lib/sinatra/show_exceptions.rb:22:in `call'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:194:in `call'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1957:in `call'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1502:in `block in call'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1729:in `synchronize'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1502:in `call'
	/var/lib/gems/2.3.0/gems/rack-2.0.7/lib/rack/auth/basic.rb:25:in `call'
	/var/lib/gems/2.3.0/gems/rack-2.0.7/lib/rack/tempfile_reaper.rb:15:in `call'
	/var/lib/gems/2.3.0/gems/rack-2.0.7/lib/rack/lint.rb:49:in `_call'
	/var/lib/gems/2.3.0/gems/rack-2.0.7/lib/rack/lint.rb:37:in `call'
	/var/lib/gems/2.3.0/gems/rack-2.0.7/lib/rack/show_exceptions.rb:23:in `call'
	/var/lib/gems/2.3.0/gems/rack-2.0.7/lib/rack/common_logger.rb:33:in `call'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:231:in `call'
	/var/lib/gems/2.3.0/gems/rack-2.0.7/lib/rack/chunked.rb:54:in `call'
	/var/lib/gems/2.3.0/gems/rack-2.0.7/lib/rack/content_length.rb:15:in `call'
	/var/lib/gems/2.3.0/gems/rack-2.0.7/lib/rack/handler/webrick.rb:86:in `service'
	/usr/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
	/usr/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
	/usr/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'
```

I'm trying to start geminabox using `rackup --host 0.0.0.0 config.ru`.
My `config.ru` is straight-forward as provided in the [readme](https://github.com/geminabox/geminabox#server-setup) with the following changes :
* `Geminbox.data` pointing to my actual data directory (obviously)
* `Rack::Auth:Basic`

I don't face this issue on version 1.1.0

**Comment by gpiucco** [comment]
Having same issue on latest version.
adding `require 'rubygems/util'` to config.ru fixes it.

**Comment by tnir** [comment]
@shinenelson You can use v1.2 or higher, in which this bug was fixed.
