### ISSUE TITLE
Errno::EINVAL at /

### ISSUE THREAD

**Issue by jfqd** [geminabox/geminabox#337]
I am using latest geminabox 1.2.0 with ruby 2.5.8, gem version is: 2.7.6.2. Upload of a gem was ok, no errors and the files are on the disk (data dir is a nfs share):

```
$ ls -al /home/ruby/www/gemserver/data
total 15
drwxr-xr-x 7 ruby ruby 13 Apr  9 12:59 .
drwxr-xr-x 5 ruby ruby  6 Apr  9 10:53 ..
drwxr-xr-x 2 ruby ruby  2 Apr  9 12:59 _cache
drwxr-xr-x 2 ruby ruby  2 Apr  9 12:59 _temp
drwxr-xr-x 2 ruby ruby  3 Apr  9 12:59 gems
-rw-r--r-- 1 ruby ruby 61 Apr  9 12:59 latest_specs.4.8
-rw-r--r-- 1 ruby ruby 78 Apr  9 12:59 latest_specs.4.8.gz
-rw-r--r-- 1 ruby ruby  4 Apr  9 12:59 prerelease_specs.4.8
-rw-r--r-- 1 ruby ruby 24 Apr  9 12:59 prerelease_specs.4.8.gz
drwxr-xr-x 3 ruby ruby  3 Apr  9 12:59 quick
-rw-r--r-- 1 ruby ruby 61 Apr  9 12:59 specs.4.8
-rw-r--r-- 1 ruby ruby 78 Apr  9 12:59 specs.4.8.gz
```

But requesting the website shows the following error:

```
Errno::EINVAL - Invalid argument @ rb_file_flock - /home/ruby/www/gemserver/data/specs.4.8.gz:
        /opt/local/lib/ruby/2.5.0/rubygems.rb:877:in `flock'
        /opt/local/lib/ruby/2.5.0/rubygems.rb:877:in `block in read_binary'
        /opt/local/lib/ruby/2.5.0/rubygems.rb:876:in `open'
        /opt/local/lib/ruby/2.5.0/rubygems.rb:876:in `read_binary'
        /opt/local/lib/ruby/gems/2.5.0/gems/geminabox-1.2.0/lib/geminabox/server.rb:269:in `block in all_gems_with_duplicates'
        /opt/local/lib/ruby/gems/2.5.0/gems/geminabox-1.2.0/lib/geminabox/server.rb:267:in `map'
        /opt/local/lib/ruby/gems/2.5.0/gems/geminabox-1.2.0/lib/geminabox/server.rb:267:in `all_gems_with_duplicates'
        /opt/local/lib/ruby/gems/2.5.0/gems/geminabox-1.2.0/lib/geminabox/server.rb:263:in `all_gems'
        /opt/local/lib/ruby/gems/2.5.0/gems/geminabox-1.2.0/lib/geminabox/server.rb:291:in `load_gems'
        /opt/local/lib/ruby/gems/2.5.0/gems/geminabox-1.2.0/lib/geminabox/server.rb:91:in `block in <class:Server>'
        /opt/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1636:in `call'
        /opt/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1636:in `block in compile!'
        /opt/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:987:in `block (3 levels) in route!'
        /opt/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1006:in `route_eval'
        /opt/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:987:in `block (2 levels) in route!'
        /opt/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1035:in `block in process_route'
        /opt/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1033:in `catch'
        /opt/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1033:in `process_route'
        /opt/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:985:in `block in route!'
        /opt/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:984:in `each'
        /opt/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:984:in `route!'
        /opt/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1098:in `block in dispatch!'
        /opt/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `block in invoke'
        /opt/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `catch'
        /opt/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `invoke'
        /opt/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1095:in `dispatch!'
        /opt/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:919:in `block in call!'
        /opt/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `block in invoke'
        /opt/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `catch'
        /opt/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `invoke'
        /opt/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:919:in `call!'
        /opt/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:908:in `call'
        /opt/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:966:in `forward'
        /opt/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1052:in `route_missing'
        /opt/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1001:in `route!'
        /opt/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:997:in `route!'
        /opt/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1098:in `block in dispatch!'
        /opt/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `block in invoke'
        /opt/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `catch'
        /opt/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `invoke'
        /opt/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1095:in `dispatch!'
        /opt/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:919:in `block in call!'
        /opt/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `block in invoke'
        /opt/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `catch'
        /opt/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `invoke'
        /opt/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:919:in `call!'
        /opt/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:908:in `call'
        /opt/local/lib/ruby/gems/2.5.0/gems/rack-protection-2.0.8.1/lib/rack/protection/xss_header.rb:18:in `call'
        /opt/local/lib/ruby/gems/2.5.0/gems/rack-protection-2.0.8.1/lib/rack/protection/path_traversal.rb:16:in `call'
        /opt/local/lib/ruby/gems/2.5.0/gems/rack-protection-2.0.8.1/lib/rack/protection/json_csrf.rb:26:in `call'
        /opt/local/lib/ruby/gems/2.5.0/gems/rack-protection-2.0.8.1/lib/rack/protection/base.rb:50:in `call'
        /opt/local/lib/ruby/gems/2.5.0/gems/rack-protection-2.0.8.1/lib/rack/protection/base.rb:50:in `call'
        /opt/local/lib/ruby/gems/2.5.0/gems/rack-protection-2.0.8.1/lib/rack/protection/frame_options.rb:31:in `call'
        /opt/local/lib/ruby/gems/2.5.0/gems/rack-2.2.2/lib/rack/null_logger.rb:11:in `call'
        /opt/local/lib/ruby/gems/2.5.0/gems/rack-2.2.2/lib/rack/head.rb:12:in `call'
        /opt/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/show_exceptions.rb:22:in `call'
        /opt/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:194:in `call'
        /opt/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1951:in `call'
        /opt/local/lib/ruby/gems/2.5.0/gems/rack-protection-2.0.8.1/lib/rack/protection/xss_header.rb:18:in `call'
        /opt/local/lib/ruby/gems/2.5.0/gems/rack-protection-2.0.8.1/lib/rack/protection/path_traversal.rb:16:in `call'
        /opt/local/lib/ruby/gems/2.5.0/gems/rack-protection-2.0.8.1/lib/rack/protection/json_csrf.rb:26:in `call'
        /opt/local/lib/ruby/gems/2.5.0/gems/rack-protection-2.0.8.1/lib/rack/protection/base.rb:50:in `call'
        /opt/local/lib/ruby/gems/2.5.0/gems/rack-protection-2.0.8.1/lib/rack/protection/base.rb:50:in `call'
        /opt/local/lib/ruby/gems/2.5.0/gems/rack-protection-2.0.8.1/lib/rack/protection/frame_options.rb:31:in `call'
        /opt/local/lib/ruby/gems/2.5.0/gems/rack-2.2.2/lib/rack/null_logger.rb:11:in `call'
        /opt/local/lib/ruby/gems/2.5.0/gems/rack-2.2.2/lib/rack/head.rb:12:in `call'
        /opt/local/lib/ruby/gems/2.5.0/gems/rack-2.2.2/lib/rack/method_override.rb:24:in `call'
        /opt/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/show_exceptions.rb:22:in `call'
        /opt/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:194:in `call'
        /opt/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1951:in `call'
        /opt/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1503:in `block in call'
        /opt/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1730:in `synchronize'
        /opt/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1503:in `call'
        /opt/local/lib/ruby/gems/2.5.0/gems/geminabox-1.2.0/lib/geminabox.rb:71:in `call'
        /opt/local/lib/ruby/gems/2.5.0/gems/thin-1.7.2/lib/thin/connection.rb:86:in `block in pre_process'
        /opt/local/lib/ruby/gems/2.5.0/gems/thin-1.7.2/lib/thin/connection.rb:84:in `catch'
        /opt/local/lib/ruby/gems/2.5.0/gems/thin-1.7.2/lib/thin/connection.rb:84:in `pre_process'
        /opt/local/lib/ruby/gems/2.5.0/gems/thin-1.7.2/lib/thin/connection.rb:53:in `process'
        /opt/local/lib/ruby/gems/2.5.0/gems/thin-1.7.2/lib/thin/connection.rb:39:in `receive_data'
        /opt/local/lib/ruby/gems/2.5.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run_machine'
        /opt/local/lib/ruby/gems/2.5.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run'
        /opt/local/lib/ruby/gems/2.5.0/gems/thin-1.7.2/lib/thin/backends/base.rb:73:in `start'
        /opt/local/lib/ruby/gems/2.5.0/gems/thin-1.7.2/lib/thin/server.rb:162:in `start'
        /opt/local/lib/ruby/gems/2.5.0/gems/thin-1.7.2/lib/thin/controllers/controller.rb:87:in `start'
        /opt/local/lib/ruby/gems/2.5.0/gems/thin-1.7.2/lib/thin/runner.rb:203:in `run_command'
        /opt/local/lib/ruby/gems/2.5.0/gems/thin-1.7.2/lib/thin/runner.rb:159:in `run!'
        /opt/local/bin/thin:6:in `<main>
```

System is a [SmartOS](https://www.joyent.com/smartos) trunk zone (Solarish system) with pkgsrc. This is like docker, but with OpenSolaris. Image build script can be found [here](https://github.com/jfqd/mi-qutic-gemsrv). Got this working with Ruby 2.4, but it fails with Ruby 2.5.

Any ideas?

**Comment by jfqd** [comment]
Think I found the issue in rubygems.rb. It only does a `rescue Errno::ENOLCK` but not a `rescue Errno::EINVAL` with nfs.

**Comment by jfqd** [comment]
Will try to get this upstream.
