### ISSUE TITLE
RuntimeError: can't add a new key into hash during iteration

### ISSUE THREAD

**Issue by ghost** [geminabox/geminabox#338]
Hi. I run geminabox with puma on Centos8, and I got errors like below occasionally when I pull gems from the server(`bundle install`).  

```log
RuntimeError: can't add a new key into hash during iteration
	/home/tkc/geminabox/vendor/bundle/ruby/2.5.0/gems/rack-2.2.2/lib/rack/session/pool.rb:50:in `store'
	/home/tkc/geminabox/vendor/bundle/ruby/2.5.0/gems/rack-2.2.2/lib/rack/session/pool.rb:50:in `block in find_session'
	/home/tkc/geminabox/vendor/bundle/ruby/2.5.0/gems/rack-2.2.2/lib/rack/session/pool.rb:73:in `with_lock'
	/home/tkc/geminabox/vendor/bundle/ruby/2.5.0/gems/rack-2.2.2/lib/rack/session/pool.rb:47:in `find_session'
	/home/tkc/geminabox/vendor/bundle/ruby/2.5.0/gems/rack-2.2.2/lib/rack/session/abstract/id.rb:314:in `load_session'
	/home/tkc/geminabox/vendor/bundle/ruby/2.5.0/gems/rack-2.2.2/lib/rack/session/abstract/id.rb:189:in `load!'
	/home/tkc/geminabox/vendor/bundle/ruby/2.5.0/gems/rack-2.2.2/lib/rack/session/abstract/id.rb:185:in `load_for_write!'
	/home/tkc/geminabox/vendor/bundle/ruby/2.5.0/gems/rack-2.2.2/lib/rack/session/abstract/id.rb:109:in `[]='
	/home/tkc/geminabox/vendor/bundle/ruby/2.5.0/gems/rack-protection-2.0.8.1/lib/rack/protection/authenticity_token.rb:116:in `set_token'
	/home/tkc/geminabox/vendor/bundle/ruby/2.5.0/gems/rack-protection-2.0.8.1/lib/rack/protection/authenticity_token.rb:100:in `accepts?'
	/home/tkc/geminabox/vendor/bundle/ruby/2.5.0/gems/rack-protection-2.0.8.1/lib/rack/protection/remote_token.rb:18:in `accepts?'
	/home/tkc/geminabox/vendor/bundle/ruby/2.5.0/gems/rack-protection-2.0.8.1/lib/rack/protection/base.rb:46:in `call'
	/home/tkc/geminabox/vendor/bundle/ruby/2.5.0/gems/rack-protection-2.0.8.1/lib/rack/protection/path_traversal.rb:16:in `call'
	/home/tkc/geminabox/vendor/bundle/ruby/2.5.0/gems/rack-protection-2.0.8.1/lib/rack/protection/json_csrf.rb:26:in `call'
	/home/tkc/geminabox/vendor/bundle/ruby/2.5.0/gems/rack-protection-2.0.8.1/lib/rack/protection/base.rb:50:in `call'
	/home/tkc/geminabox/vendor/bundle/ruby/2.5.0/gems/rack-protection-2.0.8.1/lib/rack/protection/base.rb:50:in `call'
	/home/tkc/geminabox/vendor/bundle/ruby/2.5.0/gems/rack-protection-2.0.8.1/lib/rack/protection/frame_options.rb:31:in `call'
	/home/tkc/geminabox/vendor/bundle/ruby/2.5.0/gems/rack-2.2.2/lib/rack/session/abstract/id.rb:266:in `context'
	/home/tkc/geminabox/vendor/bundle/ruby/2.5.0/gems/rack-2.2.2/lib/rack/session/abstract/id.rb:260:in `call'
	/home/tkc/geminabox/vendor/bundle/ruby/2.5.0/gems/rack-2.2.2/lib/rack/tempfile_reaper.rb:15:in `call'
	/home/tkc/geminabox/vendor/bundle/ruby/2.5.0/gems/rack-2.2.2/lib/rack/lint.rb:50:in `_call'
	/home/tkc/geminabox/vendor/bundle/ruby/2.5.0/gems/rack-2.2.2/lib/rack/lint.rb:38:in `call'
	/home/tkc/geminabox/vendor/bundle/ruby/2.5.0/gems/rack-2.2.2/lib/rack/show_exceptions.rb:23:in `call'
	/home/tkc/geminabox/vendor/bundle/ruby/2.5.0/gems/rack-2.2.2/lib/rack/common_logger.rb:38:in `call'
	/home/tkc/geminabox/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:231:in `call'
	/home/tkc/geminabox/vendor/bundle/ruby/2.5.0/gems/rack-2.2.2/lib/rack/content_length.rb:17:in `call'
	/home/tkc/geminabox/vendor/bundle/ruby/2.5.0/gems/puma-4.3.5/lib/puma/configuration.rb:228:in `call'
	/home/tkc/geminabox/vendor/bundle/ruby/2.5.0/gems/puma-4.3.5/lib/puma/server.rb:713:in `handle_request'
	/home/tkc/geminabox/vendor/bundle/ruby/2.5.0/gems/puma-4.3.5/lib/puma/server.rb:472:in `process_client'
	/home/tkc/geminabox/vendor/bundle/ruby/2.5.0/gems/puma-4.3.5/lib/puma/server.rb:328:in `block in run'
	/home/tkc/geminabox/vendor/bundle/ruby/2.5.0/gems/puma-4.3.5/lib/puma/thread_pool.rb:134:in `block in spawn_thread'
```

My puma.rb is:

```ruby
app_root = "#{File.expand_path("../..", __FILE__)}"
pidfile "#{app_root}/tmp/pids/puma.pid"
state_path "#{app_root}/tmp/pids/puma.state"
bind "unix://#{app_root}/tmp/sockets/puma.sock"
directory app_root
environment 'production'
daemonize true
stdout_redirect "/var/log/puma/production.log", "/var/log/puma/production.log", true
threads 5, 16
workers 3
```

How can I fix it?

- Environment:
  - CentOS8.1.1911
  - geminabox 1.2.0 with puma 4.3.5
  - ruby 2.5.8p224

**Comment by oshanz** [comment]
```bash
geminabox-geminabox-1  | RuntimeError: can't add a new key into hash during iteration
geminabox-geminabox-1  | 	/usr/local/bundle/gems/rack-2.2.4/lib/rack/session/pool.rb:50:in `store'
geminabox-geminabox-1  | 	/usr/local/bundle/gems/rack-2.2.4/lib/rack/session/pool.rb:50:in `block in find_session'
geminabox-geminabox-1  | 	/usr/local/bundle/gems/rack-2.2.4/lib/rack/session/pool.rb:73:in `with_lock'
geminabox-geminabox-1  | 	/usr/local/bundle/gems/rack-2.2.4/lib/rack/session/pool.rb:47:in `find_session'
geminabox-geminabox-1  | 	/usr/local/bundle/gems/rack-2.2.4/lib/rack/session/abstract/id.rb:314:in `load_session'
geminabox-geminabox-1  | 	/usr/local/bundle/gems/rack-2.2.4/lib/rack/session/abstract/id.rb:189:in `load!'
geminabox-geminabox-1  | 	/usr/local/bundle/gems/rack-2.2.4/lib/rack/session/abstract/id.rb:185:in `load_for_write!'
geminabox-geminabox-1  | 	/usr/local/bundle/gems/rack-2.2.4/lib/rack/session/abstract/id.rb:109:in `[]='
geminabox-geminabox-1  | 	/usr/local/bundle/gems/rack-protection-2.2.2/lib/rack/protection/session_hijacking.rb:25:in `accepts?'
geminabox-geminabox-1  | 	/usr/local/bundle/gems/rack-protection-2.2.2/lib/rack/protection/base.rb:46:in `call'
geminabox-geminabox-1  | 	/usr/local/bundle/gems/rack-protection-2.2.2/lib/rack/protection/base.rb:50:in `call'
geminabox-geminabox-1  | 	/usr/local/bundle/gems/rack-protection-2.2.2/lib/rack/protection/path_traversal.rb:16:in `call'
geminabox-geminabox-1  | 	/usr/local/bundle/gems/rack-protection-2.2.2/lib/rack/protection/json_csrf.rb:26:in `call'
geminabox-geminabox-1  | 	/usr/local/bundle/gems/rack-protection-2.2.2/lib/rack/protection/base.rb:50:in `call'
geminabox-geminabox-1  | 	/usr/local/bundle/gems/rack-protection-2.2.2/lib/rack/protection/base.rb:50:in `call'
geminabox-geminabox-1  | 	/usr/local/bundle/gems/rack-protection-2.2.2/lib/rack/protection/frame_options.rb:31:in `call'
geminabox-geminabox-1  | 	/usr/local/bundle/gems/rack-2.2.4/lib/rack/session/abstract/id.rb:266:in `context'
geminabox-geminabox-1  | 	/usr/local/bundle/gems/rack-2.2.4/lib/rack/session/abstract/id.rb:260:in `call'
geminabox-geminabox-1  | 	/usr/local/bundle/gems/rack-2.2.4/lib/rack/tempfile_reaper.rb:15:in `call'
geminabox-geminabox-1  | 	/usr/local/bundle/gems/rack-2.2.4/lib/rack/lint.rb:50:in `_call'
geminabox-geminabox-1  | 	/usr/local/bundle/gems/rack-2.2.4/lib/rack/lint.rb:38:in `call'
geminabox-geminabox-1  | 	/usr/local/bundle/gems/rack-2.2.4/lib/rack/show_exceptions.rb:23:in `call'
geminabox-geminabox-1  | 	/usr/local/bundle/gems/rack-2.2.4/lib/rack/common_logger.rb:38:in `call'
geminabox-geminabox-1  | 	/usr/local/bundle/gems/sinatra-2.2.2/lib/sinatra/base.rb:255:in `call'
geminabox-geminabox-1  | 	/usr/local/bundle/gems/rack-2.2.4/lib/rack/content_length.rb:17:in `call'
geminabox-geminabox-1  | 	/usr/local/bundle/gems/puma-5.6.5/lib/puma/configuration.rb:252:in `call'
geminabox-geminabox-1  | 	/usr/local/bundle/gems/puma-5.6.5/lib/puma/request.rb:77:in `block in handle_request'
geminabox-geminabox-1  | 	/usr/local/bundle/gems/puma-5.6.5/lib/puma/thread_pool.rb:340:in `with_force_shutdown'
geminabox-geminabox-1  | 	/usr/local/bundle/gems/puma-5.6.5/lib/puma/request.rb:76:in `handle_request'
geminabox-geminabox-1  | 	/usr/local/bundle/gems/puma-5.6.5/lib/puma/server.rb:443:in `process_client'
geminabox-geminabox-1  | 	/usr/local/bundle/gems/puma-5.6.5/lib/puma/thread_pool.rb:147:in `block in spawn_thread'
geminabox-geminabox-1  | RuntimeError: can't add a new key into hash during iteration
geminabox-geminabox-1  | 	/usr/local/bundle/gems/rack-2.2.4/lib/rack/session/pool.rb:50:in `store'
geminabox-geminabox-1  | 	/usr/local/bundle/gems/rack-2.2.4/lib/rack/session/pool.rb:50:in `block in find_session'
geminabox-geminabox-1  | 	/usr/local/bundle/gems/rack-2.2.4/lib/rack/session/pool.rb:73:in `with_lock'
geminabox-geminabox-1  | 	/usr/local/bundle/gems/rack-2.2.4/lib/rack/session/pool.rb:47:in `find_session'
geminabox-geminabox-1  | 	/usr/local/bundle/gems/rack-2.2.4/lib/rack/session/abstract/id.rb:314:in `load_session'
geminabox-geminabox-1  | 	/usr/local/bundle/gems/rack-2.2.4/lib/rack/session/abstract/id.rb:189:in `load!'
geminabox-geminabox-1  | 	/usr/local/bundle/gems/rack-2.2.4/lib/rack/session/abstract/id.rb:185:in `load_for_write!'
geminabox-geminabox-1  | 	/usr/local/bundle/gems/rack-2.2.4/lib/rack/session/abstract/id.rb:109:in `[]='
geminabox-geminabox-1  | 	/usr/local/bundle/gems/rack-protection-2.2.2/lib/rack/protection/session_hijacking.rb:25:in `accepts?'
geminabox-geminabox-1  | 	/usr/local/bundle/gems/rack-protection-2.2.2/lib/rack/protection/base.rb:46:in `call'
geminabox-geminabox-1  | 	/usr/local/bundle/gems/rack-protection-2.2.2/lib/rack/protection/base.rb:50:in `call'
geminabox-geminabox-1  | 	/usr/local/bundle/gems/rack-protection-2.2.2/lib/rack/protection/path_traversal.rb:16:in `call'
geminabox-geminabox-1  | 	/usr/local/bundle/gems/rack-protection-2.2.2/lib/rack/protection/json_csrf.rb:26:in `call'
geminabox-geminabox-1  | 	/usr/local/bundle/gems/rack-protection-2.2.2/lib/rack/protection/base.rb:50:in `call'
geminabox-geminabox-1  | 	/usr/local/bundle/gems/rack-protection-2.2.2/lib/rack/protection/base.rb:50:in `call'
geminabox-geminabox-1  | 	/usr/local/bundle/gems/rack-protection-2.2.2/lib/rack/protection/frame_options.rb:31:in `call'
geminabox-geminabox-1  | 	/usr/local/bundle/gems/rack-2.2.4/lib/rack/session/abstract/id.rb:266:in `context'
geminabox-geminabox-1  | 	/usr/local/bundle/gems/rack-2.2.4/lib/rack/session/abstract/id.rb:260:in `call'
geminabox-geminabox-1  | 	/usr/local/bundle/gems/rack-2.2.4/lib/rack/tempfile_reaper.rb:15:in `call'
geminabox-geminabox-1  | 	/usr/local/bundle/gems/rack-2.2.4/lib/rack/lint.rb:50:in `_call'
geminabox-geminabox-1  | 	/usr/local/bundle/gems/rack-2.2.4/lib/rack/lint.rb:38:in `call'
geminabox-geminabox-1  | 	/usr/local/bundle/gems/rack-2.2.4/lib/rack/show_exceptions.rb:23:in `call'
geminabox-geminabox-1  | 	/usr/local/bundle/gems/rack-2.2.4/lib/rack/common_logger.rb:38:in `call'
geminabox-geminabox-1  | 	/usr/local/bundle/gems/sinatra-2.2.2/lib/sinatra/base.rb:255:in `call'
geminabox-geminabox-1  | 	/usr/local/bundle/gems/rack-2.2.4/lib/rack/content_length.rb:17:in `call'
geminabox-geminabox-1  | 	/usr/local/bundle/gems/puma-5.6.5/lib/puma/configuration.rb:252:in `call'
geminabox-geminabox-1  | 	/usr/local/bundle/gems/puma-5.6.5/lib/puma/request.rb:77:in `block in handle_request'
geminabox-geminabox-1  | 	/usr/local/bundle/gems/puma-5.6.5/lib/puma/thread_pool.rb:340:in `with_force_shutdown'
geminabox-geminabox-1  | 	/usr/local/bundle/gems/puma-5.6.5/lib/puma/request.rb:76:in `handle_request'
geminabox-geminabox-1  | 	/usr/local/bundle/gems/puma-5.6.5/lib/puma/server.rb:443:in `process_client'
geminabox-geminabox-1  | 	/usr/local/bundle/gems/puma-5.6.5/lib/puma/thread_pool.rb:147:in `block in spawn_thread'
```

I can confirm this issue still exists in the latest version.
This is my setup. https://github.com/oshanz/geminabox
I have set these configurations for the puma
```
workers 2
threads 2,6
preload_app!
```
and did `bundle install --jobs 8`
some of the requests failed with the above error

**Comment by oshanz** [comment]
Some interesting findings

> So, falcon serve is the preferred method for starting a server.
>RACK_HANDLER=falcon rails server works but is limited to using the rack handler, which only starts one thread.
>bundle exec rackup -s falcon -r falcon is essentially the same as the above.
https://github.com/socketry/falcon/issues/14#issuecomment-412308022

>Yes, with rackup -s thin it's running single-threaded, that's the problem.
>thin --threaded start should work to run thin in threaded mode. The
default Rack handler for Thin not using threaded mode is a decision of the
Thin project, not the Sinatra project.
https://github.com/sinatra/sinatra/issues/937#issuecomment-60746848
