### ISSUE TITLE
rake test fails with capybara 3.37.0+ on Ruby 3.0

### ISSUE THREAD

**Issue by tnir** [geminabox/geminabox#373]
`rake test` fails with capybara 3.37.0+ (tested with 3.37.0 and 3.37.1) on Ruby 3.0.0.

`rake test` never fails with capybara 3.35.3 and 3.36.0 even on Ruby 3.0.0.

## Error log

```
  1) Error:
LargeGemListSpec#test_method: more than 5 versions of the same gem :
URI::InvalidURIError: bad URI(is not URI?): nil
    /opt/hostedtoolcache/Ruby/3.0.0/x64/lib/ruby/3.0.0/uri/rfc3986_parser.rb:18:in `rescue in split'
    /opt/hostedtoolcache/Ruby/3.0.0/x64/lib/ruby/3.0.0/uri/rfc3986_parser.rb:15:in `split'
    /opt/hostedtoolcache/Ruby/3.0.0/x64/lib/ruby/3.0.0/uri/rfc3986_parser.rb:72:in `parse'
    /opt/hostedtoolcache/Ruby/3.0.0/x64/lib/ruby/3.0.0/uri/common.rb:171:in `parse'
    /home/runner/work/geminabox/geminabox/vendor/bundle/ruby/3.0.0/gems/capybara-3.37.0/lib/capybara/rack_test/browser.rb:76:in `build_uri'
    /home/runner/work/geminabox/geminabox/vendor/bundle/ruby/3.0.0/gems/capybara-3.37.0/lib/capybara/rack_test/browser.rb:175:in `referer_url'
    /home/runner/work/geminabox/geminabox/vendor/bundle/ruby/3.0.0/gems/capybara-3.37.0/lib/capybara/rack_test/browser.rb:42:in `follow'
    /home/runner/work/geminabox/geminabox/vendor/bundle/ruby/3.0.0/gems/capybara-3.37.0/lib/capybara/rack_test/node.rb:249:in `follow_link'
    /home/runner/work/geminabox/geminabox/vendor/bundle/ruby/3.0.0/gems/capybara-3.37.0/lib/capybara/rack_test/node.rb:72:in `click'
    /home/runner/work/geminabox/geminabox/vendor/bundle/ruby/3.0.0/gems/capybara-3.37.0/lib/capybara/rack_test/node.rb:138:in `call'
    /home/runner/work/geminabox/geminabox/vendor/bundle/ruby/3.0.0/gems/capybara-3.37.0/lib/capybara/rack_test/node.rb:138:in `click'
    /home/runner/work/geminabox/geminabox/vendor/bundle/ruby/3.0.0/gems/capybara-mechanize-1.12.0/lib/capybara/mechanize/node.rb:13:in `click'
    /home/runner/work/geminabox/geminabox/vendor/bundle/ruby/3.0.0/gems/capybara-3.37.0/lib/capybara/node/element.rb:172:in `block in click'
    /home/runner/work/geminabox/geminabox/vendor/bundle/ruby/3.0.0/gems/capybara-3.37.0/lib/capybara/node/element.rb:608:in `block in perform_click_action'
    /home/runner/work/geminabox/geminabox/vendor/bundle/ruby/3.0.0/gems/capybara-3.37.0/lib/capybara/node/base.rb:83:in `synchronize'
    /home/runner/work/geminabox/geminabox/vendor/bundle/ruby/3.0.0/gems/capybara-3.37.0/lib/capybara/node/element.rb:608:in `perform_click_action'
    /home/runner/work/geminabox/geminabox/vendor/bundle/ruby/3.0.0/gems/capybara-3.37.0/lib/capybara/node/element.rb:171:in `click'
    /home/runner/work/geminabox/geminabox/vendor/bundle/ruby/3.0.0/gems/capybara-3.37.0/lib/capybara/node/actions.rb:42:in `click_link'
    /home/runner/work/geminabox/geminabox/vendor/bundle/ruby/3.0.0/gems/capybara-3.37.0/lib/capybara/session.rb:771:in `click_link'
    /home/runner/work/geminabox/geminabox/test/integration/web_interface/large_gem_list_test.rb:32:in `block in <class:LargeGemListSpec>'

27 runs, 95 assertions, 0 failures, 1 errors, 0 skips
rake aborted!
Command failed with status (1)
/home/runner/work/geminabox/geminabox/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/opt/hostedtoolcache/Ruby/3.0.0/x64/bin/bundle:23:in `load'
/opt/hostedtoolcache/Ruby/3.0.0/x64/bin/bundle:23:in `<main>'
Tasks: TOP => default => test => test:integration
(See full trace by running task with --trace)
Error: Process completed with exit code 1.
```
Adapted from https://github.com/tnir/geminabox/runs/6690031565?check_suite_focus=true

## Solution
Pin capybara to 3.36.x (`~> 3.36.0`) on test for Ruby 3.0+.

**Comment by tnir** [comment]
Closing as https://github.com/geminabox/geminabox/pull/360 resolved the problems on CI.
