### ISSUE TITLE
NameError - uninitialized constant Geminabox::VERSION

### ISSUE THREAD

**Issue by nelsnelson** [geminabox/geminabox#506]
Getting the following error when using `bundler` to install and run `geminabox`.

```ruby
NameError - uninitialized constant Geminabox::VERSION
```

My local project `Gemfile`:

```ruby
# encoding: utf-8
# frozen_string_literal: false

# -*- mode: ruby -*-
# vi: set ft=ruby :

source 'https://rubygems.org'

gemspec

group :development do
  gem 'geminabox'
  gem 'webrick'
end
```

Installation commands include:

```sh
bundle install
mkdir -p .geminabox/data
cat << EOF | tee .geminabox/config.ru
require "rubygems"
require "geminabox"

Geminabox.data = "./data"
run Geminabox::Server
EOF
bundle exec rackup .geminabox/config.ru
```

Then, when running this command:

```sh
bundle exec gem inabox ./myamazinggem-0.0.1.gem
```

The error with stacktrace is printed by `webrick`:

```rb
[2022-12-05 21:30:24] INFO  WEBrick 1.7.0
[2022-12-05 21:30:24] INFO  ruby 3.1.2 (2022-04-12) [arm64-darwin21]
[2022-12-05 21:30:24] INFO  WEBrick::HTTPServer#start: pid=52513 port=9292
2022-12-05 21:30:29 - NameError - uninitialized constant Geminabox::VERSION

      headers 'X-Powered-By' => "geminabox #{Geminabox::VERSION}"
                                                      ^^^^^^^^^
Did you mean?  Geminabox::GemVersion:
  vendor/bundle/ruby/3.1.0/gems/geminabox-2.1.0/lib/geminabox/server.rb:88:in `block in <class:Server>'
  vendor/bundle/ruby/3.1.0/gems/sinatra-2.2.3/lib/sinatra/base.rb:1693:in `call'
  vendor/bundle/ruby/3.1.0/gems/sinatra-2.2.3/lib/sinatra/base.rb:1693:in `block in compile!'
  vendor/bundle/ruby/3.1.0/gems/sinatra-2.2.3/lib/sinatra/base.rb:1078:in `block in process_route'
  vendor/bundle/ruby/3.1.0/gems/sinatra-2.2.3/lib/sinatra/base.rb:1076:in `catch'
  vendor/bundle/ruby/3.1.0/gems/sinatra-2.2.3/lib/sinatra/base.rb:1076:in `process_route'
  vendor/bundle/ruby/3.1.0/gems/sinatra-2.2.3/lib/sinatra/base.rb:1017:in `block in filter!'
  vendor/bundle/ruby/3.1.0/gems/sinatra-2.2.3/lib/sinatra/base.rb:1016:in `each'
  vendor/bundle/ruby/3.1.0/gems/sinatra-2.2.3/lib/sinatra/base.rb:1016:in `filter!'
  vendor/bundle/ruby/3.1.0/gems/sinatra-2.2.3/lib/sinatra/base.rb:1144:in `block in dispatch!'
  vendor/bundle/ruby/3.1.0/gems/sinatra-2.2.3/lib/sinatra/base.rb:1119:in `block in invoke'
  vendor/bundle/ruby/3.1.0/gems/sinatra-2.2.3/lib/sinatra/base.rb:1119:in `catch'
  vendor/bundle/ruby/3.1.0/gems/sinatra-2.2.3/lib/sinatra/base.rb:1119:in `invoke'
  vendor/bundle/ruby/3.1.0/gems/sinatra-2.2.3/lib/sinatra/base.rb:1142:in `dispatch!'
  vendor/bundle/ruby/3.1.0/gems/sinatra-2.2.3/lib/sinatra/base.rb:956:in `block in call!'
  vendor/bundle/ruby/3.1.0/gems/sinatra-2.2.3/lib/sinatra/base.rb:1119:in `block in invoke'
  vendor/bundle/ruby/3.1.0/gems/sinatra-2.2.3/lib/sinatra/base.rb:1119:in `catch'
  vendor/bundle/ruby/3.1.0/gems/sinatra-2.2.3/lib/sinatra/base.rb:1119:in `invoke'
  vendor/bundle/ruby/3.1.0/gems/sinatra-2.2.3/lib/sinatra/base.rb:956:in `call!'
  vendor/bundle/ruby/3.1.0/gems/sinatra-2.2.3/lib/sinatra/base.rb:945:in `call'
  vendor/bundle/ruby/3.1.0/gems/sinatra-2.2.3/lib/sinatra/base.rb:1003:in `forward'
  vendor/bundle/ruby/3.1.0/gems/sinatra-2.2.3/lib/sinatra/base.rb:1095:in `route_missing'
  vendor/bundle/ruby/3.1.0/gems/sinatra-2.2.3/lib/sinatra/base.rb:1044:in `route!'
  vendor/bundle/ruby/3.1.0/gems/sinatra-2.2.3/lib/sinatra/base.rb:1040:in `route!'
  vendor/bundle/ruby/3.1.0/gems/sinatra-2.2.3/lib/sinatra/base.rb:1147:in `block in dispatch!'
  vendor/bundle/ruby/3.1.0/gems/sinatra-2.2.3/lib/sinatra/base.rb:1119:in `block in invoke'
  vendor/bundle/ruby/3.1.0/gems/sinatra-2.2.3/lib/sinatra/base.rb:1119:in `catch'
  vendor/bundle/ruby/3.1.0/gems/sinatra-2.2.3/lib/sinatra/base.rb:1119:in `invoke'
  vendor/bundle/ruby/3.1.0/gems/sinatra-2.2.3/lib/sinatra/base.rb:1142:in `dispatch!'
  vendor/bundle/ruby/3.1.0/gems/sinatra-2.2.3/lib/sinatra/base.rb:956:in `block in call!'
  vendor/bundle/ruby/3.1.0/gems/sinatra-2.2.3/lib/sinatra/base.rb:1119:in `block in invoke'
  vendor/bundle/ruby/3.1.0/gems/sinatra-2.2.3/lib/sinatra/base.rb:1119:in `catch'
  vendor/bundle/ruby/3.1.0/gems/sinatra-2.2.3/lib/sinatra/base.rb:1119:in `invoke'
  vendor/bundle/ruby/3.1.0/gems/sinatra-2.2.3/lib/sinatra/base.rb:956:in `call!'
  vendor/bundle/ruby/3.1.0/gems/sinatra-2.2.3/lib/sinatra/base.rb:945:in `call'
  vendor/bundle/ruby/3.1.0/gems/rack-protection-2.2.3/lib/rack/protection/xss_header.rb:18:in `call'
  vendor/bundle/ruby/3.1.0/gems/rack-protection-2.2.3/lib/rack/protection/path_traversal.rb:16:in `call'
  vendor/bundle/ruby/3.1.0/gems/rack-protection-2.2.3/lib/rack/protection/json_csrf.rb:26:in `call'
  vendor/bundle/ruby/3.1.0/gems/rack-protection-2.2.3/lib/rack/protection/base.rb:50:in `call'
  vendor/bundle/ruby/3.1.0/gems/rack-protection-2.2.3/lib/rack/protection/base.rb:50:in `call'
  vendor/bundle/ruby/3.1.0/gems/rack-protection-2.2.3/lib/rack/protection/frame_options.rb:31:in `call'
  vendor/bundle/ruby/3.1.0/gems/rack-2.2.4/lib/rack/null_logger.rb:11:in `call'
  vendor/bundle/ruby/3.1.0/gems/rack-2.2.4/lib/rack/head.rb:12:in `call'
  vendor/bundle/ruby/3.1.0/gems/sinatra-2.2.3/lib/sinatra/show_exceptions.rb:22:in `call'
  vendor/bundle/ruby/3.1.0/gems/sinatra-2.2.3/lib/sinatra/base.rb:218:in `call'
  vendor/bundle/ruby/3.1.0/gems/sinatra-2.2.3/lib/sinatra/base.rb:2000:in `call'
  vendor/bundle/ruby/3.1.0/gems/rack-protection-2.2.3/lib/rack/protection/xss_header.rb:18:in `call'
  vendor/bundle/ruby/3.1.0/gems/rack-protection-2.2.3/lib/rack/protection/path_traversal.rb:16:in `call'
  vendor/bundle/ruby/3.1.0/gems/rack-protection-2.2.3/lib/rack/protection/json_csrf.rb:26:in `call'
  vendor/bundle/ruby/3.1.0/gems/rack-protection-2.2.3/lib/rack/protection/base.rb:50:in `call'
  vendor/bundle/ruby/3.1.0/gems/rack-protection-2.2.3/lib/rack/protection/base.rb:50:in `call'
  vendor/bundle/ruby/3.1.0/gems/rack-protection-2.2.3/lib/rack/protection/frame_options.rb:31:in `call'
  vendor/bundle/ruby/3.1.0/gems/rack-2.2.4/lib/rack/null_logger.rb:11:in `call'
  vendor/bundle/ruby/3.1.0/gems/rack-2.2.4/lib/rack/head.rb:12:in `call'
  vendor/bundle/ruby/3.1.0/gems/rack-2.2.4/lib/rack/method_override.rb:24:in `call'
  vendor/bundle/ruby/3.1.0/gems/sinatra-2.2.3/lib/sinatra/show_exceptions.rb:22:in `call'
  vendor/bundle/ruby/3.1.0/gems/sinatra-2.2.3/lib/sinatra/base.rb:218:in `call'
  vendor/bundle/ruby/3.1.0/gems/sinatra-2.2.3/lib/sinatra/base.rb:2000:in `call'
  vendor/bundle/ruby/3.1.0/gems/sinatra-2.2.3/lib/sinatra/base.rb:1560:in `block in call'
  vendor/bundle/ruby/3.1.0/gems/sinatra-2.2.3/lib/sinatra/base.rb:1776:in `synchronize'
  vendor/bundle/ruby/3.1.0/gems/sinatra-2.2.3/lib/sinatra/base.rb:1560:in `call'
  vendor/bundle/ruby/3.1.0/gems/rack-2.2.4/lib/rack/tempfile_reaper.rb:15:in `call'
  vendor/bundle/ruby/3.1.0/gems/rack-2.2.4/lib/rack/lint.rb:50:in `_call'
  vendor/bundle/ruby/3.1.0/gems/rack-2.2.4/lib/rack/lint.rb:38:in `call'
  vendor/bundle/ruby/3.1.0/gems/rack-2.2.4/lib/rack/show_exceptions.rb:23:in `call'
  vendor/bundle/ruby/3.1.0/gems/rack-2.2.4/lib/rack/common_logger.rb:38:in `call'
  vendor/bundle/ruby/3.1.0/gems/sinatra-2.2.3/lib/sinatra/base.rb:255:in `call'
  vendor/bundle/ruby/3.1.0/gems/rack-2.2.4/lib/rack/content_length.rb:17:in `call'
  vendor/bundle/ruby/3.1.0/gems/rack-2.2.4/lib/rack/handler/webrick.rb:95:in `service'
  vendor/bundle/ruby/3.1.0/gems/webrick-1.7.0/lib/webrick/httpserver.rb:140:in `service'
  vendor/bundle/ruby/3.1.0/gems/webrick-1.7.0/lib/webrick/httpserver.rb:96:in `run'
  vendor/bundle/ruby/3.1.0/gems/webrick-1.7.0/lib/webrick/server.rb:310:in `block in start_thread'

```

System information:

```sh
$ bundle exec gem list geminabox webrick

*** LOCAL GEMS ***

geminabox (2.1.0)

*** LOCAL GEMS ***

webrick (1.7.0)
$ ruby --version
ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [arm64-darwin21]
$ uname -a
Darwin laptop.local 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:52 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T8112 arm64
```

**Comment by nelsnelson** [comment]
FWIW, same thing happens if I change directory to `.geminabox` and just run `bundle exec rackup`.

**Comment by nelsnelson** [comment]
Yeah, so if I edit `geminabox-2.1.0/lib/geminabox/server.rb` and just put `VERSION = '2.1.0'` at the top of the `Geminabox` module, everything works fine.

**Comment by nelsnelson** [comment]
I have submitted a patch PR for this, but no one is reviewing it.  I am a first time committer.

**Comment by nelsnelson** [comment]
> Could you update this issue?

This Pull Request was approved: https://github.com/geminabox/geminabox/pull/514#pullrequestreview-1333888074

Can I have this issue re-opened and linked to the Pull Request?

**Comment by nelsnelson** [comment]
I guess a code owner is required to re-open this issue.  :(

**Comment by nelsnelson** [comment]
Commenting on this issue to prevent it from going stale.

**Comment by nelsnelson** [comment]
Commenting on this issue again to keep it from going stale.

@tnir is there something I'm missing here?  Would it be possible to merge the related PR?

**Comment by nelsnelson** [comment]
Oh, I have to update the issue?

**Comment by nelsnelson** [comment]
@tnir Would it still be possible to reopen this issue, and merge the related PR?  Looks like you marked my last question with a thumbs up, but it is still closed.  :(
