### ISSUE TITLE
Docker error on start: handler.rb:45:in `pick': Couldn't find handler for: puma, thin, falcon, webrick. (LoadError)

### ISSUE THREAD

**Issue by mkezys** [geminabox/geminabox#545]
docker run -it -p 9292:9292 geminabox:latest
/usr/local/bundle/gems/rack-2.2.7/lib/rack/handler.rb:45:in `pick': Couldn't find handler for: puma, thin, falcon, webrick. (LoadError)
        from /usr/local/bundle/gems/rack-2.2.7/lib/rack/handler.rb:60:in `default'
        from /usr/local/bundle/gems/rack-2.2.7/lib/rack/server.rb:334:in `server'
        from /usr/local/bundle/gems/rack-2.2.7/lib/rack/server.rb:255:in `block in logging_middleware'
        from /usr/local/bundle/gems/rack-2.2.7/lib/rack/server.rb:413:in `block in build_app'
        from /usr/local/bundle/gems/rack-2.2.7/lib/rack/server.rb:412:in `reverse_each'
        from /usr/local/bundle/gems/rack-2.2.7/lib/rack/server.rb:412:in `build_app'
        from /usr/local/bundle/gems/rack-2.2.7/lib/rack/server.rb:422:in `wrapped_app'
        from /usr/local/bundle/gems/rack-2.2.7/lib/rack/server.rb:312:in `block in start'
        from /usr/local/bundle/gems/rack-2.2.7/lib/rack/server.rb:379:in `handle_profiling'
        from /usr/local/bundle/gems/rack-2.2.7/lib/rack/server.rb:311:in `start'
        from /usr/local/bundle/gems/rack-2.2.7/lib/rack/server.rb:168:in `start'
        from /usr/local/bundle/gems/rack-2.2.7/bin/rackup:5:in `<top (required)>'
        from /usr/local/bundle/bin/rackup:25:in `load'
        from /usr/local/bundle/bin/rackup:25:in `<main>'

**Comment by mkezys** [comment]
had to add gem 'webrick' into Gemfile. Worth to mention this in the documentation.
