### ISSUE TITLE
Error on initialization: Stack level too deep

### ISSUE THREAD

**Issue by elondres-mim** [geminabox/geminabox#607]
Hi, I followed the README to set up a geminabox server, but when I run `rackup` or `puma` I get a long list of "Warning: already initialized constant Gem::VERSION" errors and then ".;.. 9348 levels ..." "rubygems/dependency.rb:38 in `initialize`: stack level too deep"

I am running Ruby 3.2, is that supported by geminabox?

**Comment by jgoodw1n** [comment]
I am running into the same issue upgrading an instance of geminabox running on Ruby 3.0.6 to Ruby 3.1.6.

**Comment by elondres-mim** [comment]
> Could you update this issue?

Still waiting to hear back about it.

**Comment by elondres-mim** [comment]
> Could you update this issue?

Still waiting to hear back about it.

**Comment by tindron** [comment]
I ran into the same issue after upgrading to rubygems 3.5.23.  I had to downgrade to 3.4.22 before geminabox would work again.

**Comment by elondres-mim** [comment]
> Could you update this issue?

Still waiting to hear back about it.

**Comment by Hammit** [comment]
I just installed geminabox the other day and it seems the highest supported Ruby is 3.1. I'm successfully using 3.1.6, although, I'd like to use 3.3.1, which doesn't work with geminabox atm.

```
<internal:/home/byron/.rbenv/versions/3.3.1/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require': cannot load such file -- rubygems/indexer (LoadError)
        from <internal:/home/byron/.rbenv/versions/3.3.1/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
        from /home/byron/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/geminabox-2.1.0/lib/geminabox.rb:8:in `<top (required)>'
        from <internal:/home/byron/.rbenv/versions/3.3.1/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
        from <internal:/home/byron/.rbenv/versions/3.3.1/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
        from /home/byron/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/geminabox-2.1.0/lib/geminabox_client.rb:5:in `<top (required)>'
        from <internal:/home/byron/.rbenv/versions/3.3.1/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
        from <internal:/home/byron/.rbenv/versions/3.3.1/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
        from /home/byron/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/geminabox-2.1.0/lib/rubygems/commands/inabox_command.rb:40:in `last_minute_requires!'
        from /home/byron/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/geminabox-2.1.0/lib/rubygems/commands/inabox_command.rb:44:in `execute'
        from /home/byron/.rbenv/versions/3.3.1/lib/ruby/3.3.0/rubygems/command.rb:326:in `invoke_with_build_args'
        from /home/byron/.rbenv/versions/3.3.1/lib/ruby/3.3.0/rubygems/command_manager.rb:255:in `invoke_command'
        from /home/byron/.rbenv/versions/3.3.1/lib/ruby/3.3.0/rubygems/command_manager.rb:194:in `process_args'
        from /home/byron/.rbenv/versions/3.3.1/lib/ruby/3.3.0/rubygems/command_manager.rb:152:in `run'
        from /home/byron/.rbenv/versions/3.3.1/lib/ruby/3.3.0/rubygems/gem_runner.rb:56:in `run'
        from /home/byron/.rbenv/versions/3.3.1/bin/gem:12:in `<main>'
```

**Comment by tindron** [comment]
> I just installed geminabox the other day and it seems the highest supported Ruby is 3.1. I'm successfully using 3.1.6, although, I'd like to use 3.3.1, which doesn't work with geminabox atm.

If you `gem update --system 3.4.22` it will work on 3.3.

**Comment by Hammit** [comment]
> > I just installed geminabox the other day and it seems the highest supported Ruby is 3.1. I'm successfully using 3.1.6, although, I'd like to use 3.3.1, which doesn't work with geminabox atm.
> 
> If you `gem update --system 3.4.22` it will work on 3.3.

That  is good to know, thankyou. For reference, I am running...

```
$ gem -v
3.5.9
```

**Comment by elondres-mim** [comment]
> Could you update this issue?

Still waiting to hear back about it.

**Comment by rvyas2** [comment]
> > > I just installed geminabox the other day and it seems the highest supported Ruby is 3.1. I'm successfully using 3.1.6, although, I'd like to use 3.3.1, which doesn't work with geminabox atm.
> > 
> > 
> > If you `gem update --system 3.4.22` it will work on 3.3.
> 
> That is good to know, thankyou. For reference, I am running...
> 
> ```
> $ gem -v
> 3.5.9
> ```

I am running into the same issue. Upgrading ruby to 3.3 or 3.4 gives this load error. ``require': cannot load such file -- rubygems/indexer (LoadError)`

3.3 using gem 3.5.22.

3.4. using gem 3.6.2.

It is working fine using ruby 3.1 (and gem 3.3.27).

**Comment by elondres-mim** [comment]
> Could you update this issue?

Still waiting to hear back about it.

**Comment by elondres-mim** [comment]
> Could you update this issue?

Still waiting to hear back about it.

**Comment by elondres-mim** [comment]
> Could you update this issue?

Still waiting to hear back about it.

**Comment by elondres-mim** [comment]
> Could you update this issue?

Still waiting to hear back about it.

**Comment by elondres-mim** [comment]
> Could you update this issue?

Still waiting to hear back about it.

**Comment by elondres-mim** [comment]
> Could you update this issue?

Still waiting to hear back about it.

**Comment by elondres-mim** [comment]
> Could you update this issue?

Still waiting to hear back about it.

**Comment by elondres-mim** [comment]
> Could you update this issue?

Still waiting to hear back about it.

**Comment by elondres-mim** [comment]
> Could you update this issue?

Still waiting to hear back about it.

**Comment by elondres-mim** [comment]
> Could you update this issue?

Still waiting to hear back about it.

**Comment by andynu** [comment]
As the discussion indicates, the extraction of `rubygems-generate_index` caused a few errors in different contexts. I could not add it as a direct dependency in version 2.2 where I added a clearer warning about it and added the deprecation warning for rubies < 3.0.0. Now that that's out, I'm releasing geminabox v3.0.0 which adds the `rubygems-generate_index` as a hard dependency. I believe that'll clear up the issues discussed here.
